const azurefilesSettings = [
	{
		label: 'Storage Account Name',
		value: 'account',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'Azure Storage Account Name. Set this to the Azure Storage Account Name in use.',
		command: '--azurefiles-account',
	},
	{
		label: 'Share Name',
		value: 'share_name',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'Azure Files Share Name. This is required and is the name of the share to access.',
		command: '--azurefiles-share-name',
	},
	{
		label: 'Storage Account Key',
		value: 'key',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'Storage Account Shared Key. Leave blank to use SAS URL or connection string.',
		command: '--azurefiles-key',
	},
	{
		label: 'SAS URL',
		value: 'sas_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'SAS URL. Leave blank if using account/key or connection string.',
		command: '--azurefiles-sas-url',
	},
	{
		label: 'Connection String',
		value: 'connection_string',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Azure Files Connection String.',
		command: '--azurefiles-connection-string',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Read credentials from runtime (environment variables, CLI or MSI). See the authentication docs for full info.',
		command: '--azurefiles-env-auth',
	},
	{
		label: 'Tenant ID',
		value: 'tenant',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"ID of the service principal's tenant, also called its directory ID.",
		command: '--azurefiles-tenant',
	},
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The ID of the client in use.',
		command: '--azurefiles-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		required: false,
		default: '',
		description: "One of the service principal's client secrets.",
		command: '--azurefiles-client-secret',
	},
	{
		label: 'Client Certificate Path',
		value: 'client_certificate_path',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to a PEM or PKCS12 certificate file including the private key.',
		command: '--azurefiles-client-certificate-path',
	},
	{
		label: 'Client Certificate Password',
		value: 'client_certificate_password',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Password for the certificate file (optional).',
		command: '--azurefiles-client-certificate-password',
	},
	{
		label: 'Send Certificate Chain',
		value: 'client_send_certificate_chain',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Send the certificate chain when using certificate auth. Specifies whether an authentication request will include an x5c header to support subject name / issuer based authentication. When set to true, authentication requests include the x5c header.',
		command: '--azurefiles-client-send-certificate-chain',
	},
	{
		label: 'Username',
		value: 'username',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'User name (usually an email address).',
		command: '--azurefiles-username',
	},
	{
		label: 'Password',
		value: 'password',
		fieldType: 'string',
		required: false,
		default: '',
		description: "The user's password.",
		command: '--azurefiles-password',
	},
	{
		label: 'Service Principal File',
		value: 'service_principal_file',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to file containing credentials for use with a service principal. Leave blank normally. Needed only if you want to use a service principal instead of interactive login.',
		command: '--azurefiles-service-principal-file',
	},
	{
		label: 'Use MSI',
		value: 'use_msi',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use a managed service identity to authenticate (only works in Azure). When true, use a managed service identity to authenticate to Azure Storage instead of a SAS token or account key.',
		command: '--azurefiles-use-msi',
	},
	{
		label: 'MSI Object ID',
		value: 'msi_object_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Object ID of the user-assigned MSI to use, if any. Leave blank if MSI Client ID or MSI Resource ID is specified.',
		command: '--azurefiles-msi-object-id',
	},
	{
		label: 'MSI Client ID',
		value: 'msi_client_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Client ID of the user-assigned MSI to use, if any. Leave blank if MSI Object ID or MSI Resource ID is specified.',
		command: '--azurefiles-msi-client-id',
	},
	{
		label: 'MSI Resource ID',
		value: 'msi_mi_res_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Azure resource ID of the user-assigned MSI to use, if any. Leave blank if MSI Client ID or MSI Object ID is specified.',
		command: '--azurefiles-msi-mi-res-id',
	},
	{
		label: 'Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Endpoint for the service. Leave blank normally.',
		command: '--azurefiles-endpoint',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '4mi',
		description:
			'Upload chunk size. Chunks are stored in memory, and memory usage depends on the number of concurrent transfers.',
		command: '--azurefiles-chunk-size',
	},
	{
		label: 'Upload Concurrency',
		value: 'upload_concurrency',
		fieldType: 'int',
		required: false,
		default: '16',
		description:
			'Concurrency for multipart uploads. This is the number of chunks of the same file that are uploaded concurrently.',
		command: '--azurefiles-upload-concurrency',
	},
	{
		label: 'Max Stream Size',
		value: 'max_stream_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '10gi',
		description:
			"Max size for streamed files. Azure Files needs to know the file size in advance. This value is used when the file size is unknown.",
		command: '--azurefiles-max-stream-size',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default:
			'slash,ltgt,doublequote,colon,question,asterisk,pipe,backslash,del,ctl,rightperiod,invalidutf8,dot',
		description:
			'The encoding for the backend.',
		command: '--azurefiles-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--azurefiles-description',
	},
];

export default azurefilesSettings;
