const azureblobSettings = [
	{
		label: 'Storage Account Name',
		value: 'account',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'Azure Storage Account Name. Set this to the Azure Storage Account Name in use.',
		command: '--azureblob-account',
	},
	{
		label: 'Storage Account Key',
		value: 'key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Storage Account Shared Key. Leave blank to use SAS URL or Emulator.',
		command: '--azureblob-key',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Read credentials from runtime (environment variables, CLI or MSI). See the authentication docs for full info.',
		command: '--azureblob-env-auth',
	},
	{
		label: 'SAS URL',
		value: 'sas_url',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'SAS URL for container level access only. Leave blank if using account/key or Emulator.',
		command: '--azureblob-sas-url',
	},
	{
		label: 'Tenant ID',
		value: 'tenant',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description:
			"ID of the service principal's tenant. Also called its directory ID. Set this if using",
		command: '--azureblob-tenant',
	},
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: 'The ID of the client in use. Set this if using',
		command: '--azureblob-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		required: false,
		default: '',
		description: "One of the service principal's client secrets Set this if using",
		command: '--azureblob-client-secret',
	},
	{
		label: 'Client Certificate Path',
		value: 'client_certificate_path',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to a PEM or PKCS12 certificate file including the private key. Set this if using',
		command: '--azureblob-client-certificate-path',
	},
	{
		label: 'Client Certificate Password',
		value: 'client_certificate_password',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Password for the certificate file (optional). Optionally set this if using',
		command: '--azureblob-client-certificate-password',
	},
	{
		label: 'Send Certificate Chain',
		value: 'client_send_certificate_chain',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Send the certificate chain when using certificate auth. Specifies whether an authentication request will include an x5c header to support subject name / issuer based authentication. When set to true, authentication requests include the x5c header.',
		command: '--azureblob-client-send-certificate-chain',
	},
	{
		label: 'Username',
		value: 'username',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: 'User name (usually an email address) Set this if using',
		command: '--azureblob-username',
	},
	{
		label: 'Password',
		value: 'password',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: "The user's password. Set this if using",
		command: '--azureblob-password',
	},
	{
		label: 'Service Principal File',
		value: 'service_principal_file',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to file containing credentials for use with a service principal. Leave blank normally. Needed only if you want to use a service principal instead of interactive login.',
		command: '--azureblob-service-principal-file',
	},
	{
		label: 'Disable Instance Discovery',
		value: 'disable_instance_discovery',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Skip requesting Microsoft Entra instance metadata This should be set true only by applications authenticating in disconnected clouds, or private clouds such as Azure Stack.',
		command: '--azureblob-disable-instance-discovery',
	},
	{
		label: 'Use MSI',
		value: 'use_msi',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use a managed service identity to authenticate (only works in Azure). When true, use a managed service identity to authenticate to Azure Storage instead of a SAS token or account key.',
		command: '--azureblob-use-msi',
	},
	{
		label: 'MSI Object ID',
		value: 'msi_object_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Object ID of the user-assigned MSI to use, if any. Leave blank if msi_client_id or msi_mi_res_id specified.',
		command: '--azureblob-msi-object-id',
	},
	{
		label: 'MSI Client ID',
		value: 'msi_client_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Object ID of the user-assigned MSI to use, if any. Leave blank if msi_object_id or msi_mi_res_id specified.',
		command: '--azureblob-msi-client-id',
	},
	{
		label: 'MSI Resource ID',
		value: 'msi_mi_res_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Azure resource ID of the user-assigned MSI to use, if any. Leave blank if msi_client_id or msi_object_id specified.',
		command: '--azureblob-msi-mi-res-id',
	},
	{
		label: 'Use Emulator',
		value: 'use_emulator',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Uses local storage emulator if provided as 'true'. Leave blank if using real azure storage endpoint.",
		command: '--azureblob-use-emulator',
	},
	{
		label: 'Use Azure CLI',
		value: 'use_az',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use Azure CLI tool az for authentication Set to use the Azure CLI tool az as the sole means of authentication.',
		command: '--azureblob-use-az',
	},
	{
		label: 'Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Endpoint for the service. Leave blank normally.',
		command: '--azureblob-endpoint',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Cutoff for switching to chunked upload (<= 256 MiB) (deprecated).',
		command: '--azureblob-upload-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '4mi',
		description:
			'Upload chunk size. Note that this is stored in memory and there may be up to "--transfers" * "--azureblob-upload-concurrency" chunks stored at once in memory.',
		command: '--azureblob-chunk-size',
	},
	{
		label: 'Upload Concurrency',
		value: 'upload_concurrency',
		fieldType: 'int',
		required: false,
		default: '16',
		description:
			'Concurrency for multipart uploads. This is the number of chunks of the same file that are uploaded concurrently.',
		command: '--azureblob-upload-concurrency',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '5000',
		description:
			'Size of blob list. This sets the number of blobs requested in each listing chunk. Default is the maximum, 5000. "List blobs" requests are permitted 2 minutes per megabyte to complete. If an operation is taking longer than 2 minutes per megabyte on average, it will time out ( source ). This can be used to limit the number of blobs items to return, to avoid the time out.',
		command: '--azureblob-list-chunk',
	},
	{
		label: 'Access Tier',
		value: 'access_tier',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Access tier of blob: hot, cool, cold or archive. Archived blobs can be restored by setting access tier to hot, cool or cold. Leave blank if you intend to use default access tier, which is set at account level',
		command: '--azureblob-access-tier',
	},
	{
		label: 'Archive Tier Delete',
		value: 'archive_tier_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Delete archive tier blobs before overwriting. Archive tier blobs cannot be updated. So without this flag, if you attempt to update an archive tier blob, then rclone will produce the error:',
		command: '--azureblob-archive-tier-delete',
	},
	{
		label: 'Disable Checksum',
		value: 'disable_checksum',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Don't store MD5 checksum with object metadata. Normally rclone will calculate the MD5 checksum of the input before uploading it so it can add it to metadata on the object. This is great for data integrity checking but can cause long delays for large files to start uploading.",
		command: '--azureblob-disable-checksum',
	},
	{
		label: 'Memory Pool Flush Time',
		value: 'memory_pool_flush_time',
		fieldType: 'duration',
		required: false,
		default: '1m0s',
		description: 'How often internal memory buffer pools will be flushed. (no longer used)',
		command: '--azureblob-memory-pool-flush-time',
	},
	{
		label: 'Memory Pool Use MMAP',
		value: 'memory_pool_use_mmap',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Whether to use mmap buffers in internal memory pool. (no longer used)',
		command: '--azureblob-memory-pool-use-mmap',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,rightperiod,invalidutf8',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--azureblob-encoding',
	},
	{
		label: 'Public Access',
		value: 'public_access',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Public access level of a container: blob or container.',
		command: '--azureblob-public-access',
	},
	{
		label: 'Directory Markers',
		value: 'directory_markers',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Upload an empty object with a trailing slash when a new directory is created Empty folders are unsupported for bucket based storages, this option creates an empty object ending with "/", to persist the folder.',
		command: '--azureblob-directory-markers',
	},
	{
		label: 'No Check Container',
		value: 'no_check_container',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"If set, don't attempt to check the container exists or create it. This can be useful when trying to minimize the number of transactions rclone does if you know the container exists already.",
		command: '--azureblob-no-check-container',
	},
	{
		label: 'No Head Object',
		value: 'no_head_object',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'If set, do not do HEAD before GET when getting objects.',
		command: '--azureblob-no-head-object',
	},
	{
		label: 'Delete Snapshots',
		value: 'delete_snapshots',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Set to specify how to deal with snapshots on blob deletion.',
		command: '--azureblob-delete-snapshots',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--azureblob-description',
	},
];

export default azureblobSettings;
