const b2Settings = [
	{
		label: 'Account ID',
		value: 'account',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Account ID or Application Key ID.',
		command: '--b2-account',
	},
	{
		label: 'Application Key',
		value: 'key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Application Key.',
		command: '--b2-key',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Permanently delete files on remote removal, otherwise hide files.',
		command: '--b2-hard-delete',
	},
	{
		label: 'Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Endpoint for the service. Leave blank normally.',
		command: '--b2-endpoint',
	},
	{
		label: 'Test Mode',
		value: 'test_mode',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'A flag string for X-Bz-Test-Mode header for debugging. This is for debugging purposes only. Setting it to one of the strings below will cause b2 to return specific errors: fail_some_uploads, expire_some_account_authorization_tokens, force_cap_exceeded',
		command: '--b2-test-mode',
	},
	{
		label: 'Include Versions',
		value: 'versions',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Include old versions in directory listings. Note that when using this no file write operations are permitted, so you can't upload files or delete them.",
		command: '--b2-versions',
	},
	{
		label: 'Version At',
		value: 'version_at',
		fieldType: 'time',
		required: false,
		default: 'off',
		description:
			"Show file versions as they were at the specified time. Note that when using this no file write operations are permitted, so you can't upload files or delete them.",
		command: '--b2-version-at',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '200mi',
		description:
			'Cutoff for switching to chunked upload. Files above this size will be uploaded in chunks of "--b2-chunk-size".',
		command: '--b2-upload-cutoff',
	},
	{
		label: 'Copy Cutoff',
		value: 'copy_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '4gi',
		description:
			'Cutoff for switching to multipart copy. Any files larger than this that need to be server-side copied will be copied in chunks of this size.',
		command: '--b2-copy-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '96mi',
		description: 'Upload chunk size. When uploading large files, chunk the file into this size.',
		command: '--b2-chunk-size',
	},
	{
		label: 'Upload Concurrency',
		value: 'upload_concurrency',
		fieldType: 'int',
		required: false,
		default: '4',
		description:
			'Concurrency for multipart uploads. This is the number of chunks of the same file that are uploaded concurrently.',
		command: '--b2-upload-concurrency',
	},
	{
		label: 'Disable Checksum',
		value: 'disable_checksum',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Disable checksums for large (> upload cutoff) files. Normally rclone will calculate the SHA1 checksum of the input before uploading it so it can add it to metadata on the object. This is great for data integrity checking but can cause long delays for large files to start uploading.',
		command: '--b2-disable-checksum',
	},
	{
		label: 'Download URL',
		value: 'download_url',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Custom endpoint for downloads. This is usually set to a Cloudflare CDN URL as Backblaze offers free egress for data downloaded through the Cloudflare network. Rclone works with private buckets by sending an "Authorization" header. If the custom endpoint rewrites the requests for authentication, e.g., in Cloudflare Workers, this header needs to be handled properly. Leave blank if you want to use the endpoint provided by Backblaze.',
		command: '--b2-download-url',
	},
	{
		label: 'Download Auth Duration',
		value: 'download_auth_duration',
		fieldType: 'duration',
		required: false,
		default: '1w',
		description:
			'Time before the public link authorization token will expire in s or suffix ms|s|m|h|d. This is used in combination with "rclone link" for making files accessible to the public and sets the duration before the download authorization token will expire.',
		command: '--b2-download-auth-duration',
	},
	{
		label: 'Memory Pool Flush Time',
		value: 'memory_pool_flush_time',
		fieldType: 'duration',
		required: false,
		default: '1m0s',
		description: 'How often internal memory buffer pools will be flushed. (no longer used)',
		command: '--b2-memory-pool-flush-time',
	},
	{
		label: 'Memory Pool Use MMAP',
		value: 'memory_pool_use_mmap',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Whether to use mmap buffers in internal memory pool. (no longer used)',
		command: '--b2-memory-pool-use-mmap',
	},
	{
		label: 'Lifecycle',
		value: 'lifecycle',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'Set the number of days deleted files should be kept when creating a bucket. On bucket creation, this parameter is used to create a lifecycle rule for the entire bucket.',
		command: '--b2-lifecycle',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--b2-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--b2-description',
	},
];

export default b2Settings;
