const boxSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id',
		command: '--box-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Secret',
		command: '--box-client-secret',
	},
	{
		label: 'Config File',
		value: 'box_config_file',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Box App config.json location. Leave blank normally.',
		command: '--box-box-config-file',
	},
	// {
	// 	label: 'Access Token',
	// 	value: 'access_token',
	// 	fieldType: 'string',
	// 	authFieldType: 'oauth',
	// 	required: false,
	// 	default: '',
	// 	description: 'Box App Primary Access Token Leave blank normally.',
	// 	command: '--box-access-token',
	// },
	// {
	// 	label: 'Sub Type',
	// 	value: 'box_sub_type',
	// 	fieldType: 'string',
	// 	authFieldType: 'oauth',
	// 	required: true,
	// 	default: 'user',
	// 	description:
	// 		'Properties: Config:      box_sub_type Env Var:     RCLONE_BOX_BOX_SUB_TYPE Type:        string Default:     "user" Examples:  "user"  Rclone should act on behalf of a user.   "enterprise"  Rclone should act on behalf of a service account.',
	// 	command: '--box-box-sub-type',
	// },
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--box-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--box-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--box-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		authFieldType: 'client',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--box-client-credentials',
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '0',
		description: 'Fill in for rclone to use a non root folder as its starting point.',
		command: '--box-root-folder-id',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '50mi',
		description: 'Cutoff for switching to multipart upload (>= 50 MiB).',
		command: '--box-upload-cutoff',
	},
	{
		label: 'Commit Retries',
		value: 'commit_retries',
		fieldType: 'int',
		required: false,
		default: '100',
		description: 'Max number of times to try committing a multipart file.',
		command: '--box-commit-retries',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '1000',
		description: 'Size of listing chunk 1-1000.',
		command: '--box-list-chunk',
	},
	{
		label: 'Owned By',
		value: 'owned_by',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Only show items owned by the login (email address) passed in.',
		command: '--box-owned-by',
	},
	{
		label: 'Impersonate User',
		value: 'impersonate',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Impersonate this user ID when using a service account. Setting this flag allows rclone, when using a JWT service account, to act on behalf of another user by setting the as-user header.',
		command: '--box-impersonate',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,rightspace,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--box-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--box-description',
	},
];

export default boxSettings;
