const drimeSettings = [
	{
		label: 'API Access Token',
		value: 'access_token',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'API Access token. You can get this from the web control panel under Settings → Developer.',
		command: '--drime-access-token',
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'ID of the root folder. Leave blank normally, it will be filled in automatically.',
		command: '--drime-root-folder-id',
	},
	{
		label: 'Workspace ID',
		value: 'workspace_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Workspace ID. Leave blank unless you need to target a specific workspace.',
		command: '--drime-workspace-id',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '1000',
		description: 'Number of items to list in each call.',
		command: '--drime-list-chunk',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Delete files permanently rather than putting them into the trash.',
		command: '--drime-hard-delete',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,leftspace,rightspace,invalidutf8,dot',
		description: 'The encoding for the backend.',
		command: '--drime-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--drime-description',
	},
];

export default drimeSettings;
