const dropboxSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--dropbox-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--dropbox-client-secret',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--dropbox-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--dropbox-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--dropbox-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description: 'Use client credentials OAuth flow instead of interactive login.',
		command: '--dropbox-client-credentials',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '48mi',
		description:
			'Upload chunk size (< 150Mi). Any files larger than this will be uploaded in chunks of this size.',
		command: '--dropbox-chunk-size',
	},
	{
		label: 'Impersonate User',
		value: 'impersonate',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Impersonate this user when using a Dropbox Business account.',
		command: '--dropbox-impersonate',
	},
	{
		label: 'Shared Files',
		value: 'shared_files',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Work with individual shared files. In this mode, only listing and downloading are supported.',
		command: '--dropbox-shared-files',
	},
	{
		label: 'Shared Folders',
		value: 'shared_folders',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Work with shared folders. When enabled without a path, all shared folders are listed. With a path, the first part is treated as the shared folder name.',
		command: '--dropbox-shared-folders',
	},
	{
		label: 'Pacer Min Sleep',
		value: 'pacer_min_sleep',
		fieldType: 'duration',
		required: false,
		default: '10ms',
		description: 'Minimum time to sleep between API calls.',
		command: '--dropbox-pacer-min-sleep',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,rightspace,invalidutf8,dot',
		description: 'Character encoding for file and folder names.',
		command: '--dropbox-encoding',
	},
	{
		label: 'Root Namespace',
		value: 'root_namespace',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Specify a different Dropbox namespace ID to use as the root for all paths.',
		command: '--dropbox-root-namespace',
	},
	{
		label: 'Batch Mode',
		value: 'batch_mode',
		fieldType: 'select',
		required: false,
		default: 'sync',
		description: 'Upload file batching mode.',
		command: '--dropbox-batch-mode',
		options: [
			{ label: 'Sync (batch and check completion)', value: 'sync' },
			{ label: 'Async (batch, no completion check)', value: 'async' },
			{ label: 'Off (no batching)', value: 'off' },
		],
	},
	{
		label: 'Batch Size',
		value: 'batch_size',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'Max number of files in upload batch. This sets the batch size of files to upload. It has to be less than 1000.',
		command: '--dropbox-batch-size',
	},
	{
		label: 'Batch Timeout',
		value: 'batch_timeout',
		fieldType: 'duration',
		required: false,
		default: '0s',
		description:
			'Max time to allow an idle upload batch before uploading. If an upload batch is idle for more than this long then it will be uploaded.',
		command: '--dropbox-batch-timeout',
	},
	{
		label: 'Batch Commit Timeout',
		value: 'batch_commit_timeout',
		fieldType: 'duration',
		required: false,
		default: '10m0s',
		description: 'Max time to wait for a batch to finish committing',
		command: '--dropbox-batch-commit-timeout',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--dropbox-description',
	},
];

export default dropboxSettings;
