const dropboxSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--dropbox-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--dropbox-client-secret',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--dropbox-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--dropbox-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--dropbox-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--dropbox-client-credentials',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '48mi',
		description:
			'Upload chunk size (< 150Mi). Any files larger than this will be uploaded in chunks of this size.',
		command: '--dropbox-chunk-size',
	},
	{
		label: 'Impersonate User',
		value: 'impersonate',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Impersonate this user when using a business account. Note that if you want to use impersonate, you should make sure this flag is set when running "rclone config" as this will cause rclone to request the "members.read" scope which it won\'t normally. This is needed to lookup a members email address into the internal ID that dropbox uses in the API.',
		command: '--dropbox-impersonate',
	},
	{
		label: 'Shared Files',
		value: 'shared_files',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Instructs rclone to work on individual shared files. In this mode rclone's features are extremely limited - only list (ls, lsl, etc.) operations and read operations (e.g. downloading) are supported in this mode. All other operations will be disabled.",
		command: '--dropbox-shared-files',
	},
	{
		label: 'Shared Folders',
		value: 'shared_folders',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Instructs rclone to work on shared folders. When this flag is used with no path only the List operation is supported and all available shared folders will be listed. If you specify a path the first part will be interpreted as the name of shared folder. Rclone will then try to mount this shared to the root namespace. On success shared folder rclone proceeds normally. The shared folder is now pretty much a normal folder and all normal operations are supported.',
		command: '--dropbox-shared-folders',
	},
	{
		label: 'Pacer Min Sleep',
		value: 'pacer_min_sleep',
		fieldType: 'duration',
		required: false,
		default: '10ms',
		description: 'Minimum time to sleep between API calls.',
		command: '--dropbox-pacer-min-sleep',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,rightspace,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--dropbox-encoding',
	},
	{
		label: 'Root Namespace',
		value: 'root_namespace',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Specify a different Dropbox namespace ID to use as the root for all paths.',
		command: '--dropbox-root-namespace',
	},
	{
		label: 'Batch Mode',
		value: 'batch_mode',
		fieldType: 'string',
		required: false,
		default: 'sync',
		description: 'Upload file batching sync|async|off. This sets the batch mode used by rclone.',
		command: '--dropbox-batch-mode',
	},
	{
		label: 'Batch Size',
		value: 'batch_size',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'Max number of files in upload batch. This sets the batch size of files to upload. It has to be less than 1000.',
		command: '--dropbox-batch-size',
	},
	{
		label: 'Batch Timeout',
		value: 'batch_timeout',
		fieldType: 'duration',
		required: false,
		default: '0s',
		description:
			'Max time to allow an idle upload batch before uploading. If an upload batch is idle for more than this long then it will be uploaded.',
		command: '--dropbox-batch-timeout',
	},
	{
		label: 'Batch Commit Timeout',
		value: 'batch_commit_timeout',
		fieldType: 'duration',
		required: false,
		default: '10m0s',
		description: 'Max time to wait for a batch to finish committing',
		command: '--dropbox-batch-commit-timeout',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--dropbox-description',
	},
];

export default dropboxSettings;
