const ftpSettings = [
	{
		label: 'FTP Host',
		command: '--ftp-host',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		value: 'host',
		default: '',
		description: 'FTP host to connect to. E.g. "ftp.example.com".',
	},
	{
		label: 'FTP Username',
		command: '--ftp-user',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		value: 'user',
		default: '$user',
		description: 'FTP username.',
	},
	{
		label: 'FTP Port',
		command: '--ftp-port',
		fieldType: 'int',
		authFieldType: 'password',
		required: false,
		value: 'port',
		default: '21',
		description: 'FTP port number.',
	},
	{
		label: 'FTP Password',
		command: '--ftp-pass',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		value: 'pass',
		default: '',
		description: 'FTP password. NB Input to this must be obscured - see rclone obscure.',
	},
	{
		label: 'Use Implicit FTPS (FTP over TLS)',
		command: '--ftp-tls',
		fieldType: 'bool',
		authFieldType: 'password',
		required: false,
		value: 'tls',
		default: false,
		description:
			'Use Implicit FTPS (FTP over TLS). When using implicit FTP over TLS the client connects using TLS\nright from the start which breaks compatibility with\nnon-TLS-aware servers. This is usually served over port 990 rather\nthan port 21. Cannot be used in combination with explicit FTPS.',
	},
	{
		label: 'Use Explicit FTPS (FTP over TLS)',
		command: '--ftp-explicit-tls',
		fieldType: 'bool',
		authFieldType: 'password',
		required: false,
		value: 'explicit_tls',
		default: false,
		description:
			'Use Explicit FTPS (FTP over TLS). When using explicit FTP over TLS the client explicitly requests\nsecurity from the server in order to upgrade a plain text connection\nto an encrypted one. Cannot be used in combination with implicit FTPS.',
	},
	{
		label: 'Max FTP Simultaneous Connections',
		command: '--ftp-concurrency',
		fieldType: 'int',
		required: false,
		value: 'concurrency',
		default: '0',
		description:
			'Maximum number of FTP simultaneous connections, 0 for unlimited. Note that setting this is very likely to cause deadlocks so it should\nbe used with care.',
	},
	{
		label: 'Do Not Verify TLS Certificate',
		command: '--ftp-no-check-certificate',
		fieldType: 'bool',
		required: false,
		value: 'no_check_certificate',
		default: false,
		description: 'Do not verify the TLS certificate of the server.',
	},
	{
		label: 'Disable EPSV',
		command: '--ftp-disable-epsv',
		fieldType: 'bool',
		required: false,
		value: 'disable_epsv',
		default: false,
		description: 'Disable using EPSV even if server advertises support.',
	},
	{
		label: 'Disable MLSD',
		command: '--ftp-disable-mlsd',
		fieldType: 'bool',
		required: false,
		value: 'disable_mlsd',
		default: false,
		description: 'Disable using MLSD even if server advertises support.',
	},
	{
		label: 'Disable UTF-8',
		command: '--ftp-disable-utf8',
		fieldType: 'bool',
		required: false,
		value: 'disable_utf8',
		default: false,
		description: 'Disable using UTF-8 even if server advertises support.',
	},
	{
		label: 'Use MDTM to Set Modification Time',
		command: '--ftp-writing-mdtm',
		fieldType: 'bool',
		required: false,
		value: 'writing_mdtm',
		default: false,
		description: 'Use MDTM to set modification time (VsFtpd quirk)',
	},
	{
		label: 'Force Listing of Hidden Files',
		command: '--ftp-force-list-hidden',
		fieldType: 'bool',
		required: false,
		value: 'force_list_hidden',
		default: false,
		description:
			'Use LIST -a to force listing of hidden files and folders. This will disable the use of MLSD.',
	},
	{
		label: 'Idle Connection Timeout',
		command: '--ftp-idle-timeout',
		fieldType: 'duration',
		required: false,
		value: 'idle_timeout',
		default: '1m0s',
		description:
			'Max time before closing idle connections. If no connections have been returned to the connection pool in the time\ngiven, rclone will empty the connection pool.',
	},
	{
		label: 'Close Response Timeout',
		command: '--ftp-close-timeout',
		fieldType: 'duration',
		required: false,
		value: 'close_timeout',
		default: '1m0s',
		description: 'Maximum time to wait for a response to close.',
	},
	{
		label: 'TLS Session Cache Size',
		command: '--ftp-tls-cache-size',
		fieldType: 'int',
		required: false,
		value: 'tls_cache_size',
		default: '32',
		description:
			'Size of TLS session cache for all control and data connections. TLS cache allows to resume TLS sessions and reuse PSK between connections.\nIncrease if default size is not enough resulting in TLS resumption errors.\nEnabled by default. Use 0 to disable.',
	},
	{
		label: 'Disable TLS 1.3',
		command: '--ftp-disable-tls13',
		fieldType: 'bool',
		required: false,
		value: 'disable_tls13',
		default: false,
		description: 'Disable TLS 1.3 (workaround for FTP servers with buggy TLS)',
	},
	{
		label: 'Data Connection Close Timeout',
		command: '--ftp-shut-timeout',
		fieldType: 'duration',
		required: false,
		value: 'shut_timeout',
		default: '1m0s',
		description: 'Maximum time to wait for data connection closing status.',
	},
	{
		label: 'Allow Asking for FTP Password',
		command: '--ftp-ask-password',
		fieldType: 'bool',
		required: false,
		value: 'ask_password',
		default: false,
		description:
			'Allow asking for FTP password when needed. If this is set and no password is supplied then rclone will ask for a password',
	},
	{
		label: 'SOCKS Proxy',
		command: '--ftp-socks-proxy',
		fieldType: 'string',
		required: false,
		value: 'socks_proxy',
		default: '',
		description:
			'Socks 5 proxy host. Supports the format user:pass@host:port, user@host:port, host:port.',
	},
	{
		label: "Don't Check Upload",
		command: '--ftp-no-check-upload',
		fieldType: 'bool',
		required: false,
		value: 'no_check_upload',
		default: false,
		description:
			"Don't check the upload is OK Normally rclone will try to check the upload exists after it has\nuploaded a file to make sure the size and modification time are as\nexpected.",
	},
	{
		label: 'Backend Encoding',
		command: '--ftp-encoding',
		fieldType: 'encoding',
		required: false,
		value: 'encoding',
		default: 'slash,del,ctl,rightspace,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
	},
	{
		label: 'Description',
		command: '--ftp-description',
		fieldType: 'string',
		required: false,
		value: 'description',
		default: '',
		description: 'Description of the Storage.',
	},
];

export default ftpSettings;
