import type { ProviderSetting } from './types';

const ftpSettings: ProviderSetting[] = [
	{
		label: 'FTP Host',
		command: '--ftp-host',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		value: 'host',
		default: '',
		description: 'FTP host to connect to. E.g. "ftp.example.com".',
	},
	{
		label: 'FTP Username',
		command: '--ftp-user',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		value: 'user',
		default: '$user',
		description: 'FTP username.',
	},
	{
		label: 'FTP Port',
		command: '--ftp-port',
		fieldType: 'int',
		authFieldType: 'password',
		required: false,
		value: 'port',
		default: '21',
		description: 'FTP port number.',
	},
	{
		label: 'FTP Password',
		command: '--ftp-pass',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		value: 'pass',
		default: '',
		description: 'FTP password.',
	},
	{
		label: 'Use Implicit FTPS (FTP over TLS)',
		command: '--ftp-tls',
		fieldType: 'bool',
		authFieldType: 'password',
		required: false,
		value: 'tls',
		default: false,
		description:
			'Use Implicit FTPS (FTP over TLS). Connects using TLS from the start, usually on port 990. Cannot be used with explicit FTPS.',
	},
	{
		label: 'Use Explicit FTPS (FTP over TLS)',
		command: '--ftp-explicit-tls',
		fieldType: 'bool',
		authFieldType: 'password',
		required: false,
		value: 'explicit_tls',
		default: false,
		description:
			'Use Explicit FTPS (FTP over TLS). Upgrades a plain text connection to encrypted. Cannot be used with implicit FTPS.',
	},
	{
		label: 'Max FTP Simultaneous Connections',
		command: '--ftp-concurrency',
		fieldType: 'int',
		required: false,
		value: 'concurrency',
		default: '0',
		description:
			'Maximum number of FTP simultaneous connections, 0 for unlimited. Setting this is likely to cause deadlocks, so use with care.',
	},
	{
		label: 'Do Not Verify TLS Certificate',
		command: '--ftp-no-check-certificate',
		fieldType: 'bool',
		required: false,
		value: 'no_check_certificate',
		default: false,
		description: 'Do not verify the TLS certificate of the server.',
		condition: [{ tls: true }, { explicit_tls: true }],
	},
	{
		label: 'Disable EPSV',
		command: '--ftp-disable-epsv',
		fieldType: 'bool',
		required: false,
		value: 'disable_epsv',
		default: false,
		description: 'Disable using EPSV even if server advertises support.',
	},
	{
		label: 'Disable MLSD',
		command: '--ftp-disable-mlsd',
		fieldType: 'bool',
		required: false,
		value: 'disable_mlsd',
		default: false,
		description: 'Disable using MLSD even if server advertises support.',
	},
	{
		label: 'Disable UTF-8',
		command: '--ftp-disable-utf8',
		fieldType: 'bool',
		required: false,
		value: 'disable_utf8',
		default: false,
		description: 'Disable using UTF-8 even if server advertises support.',
	},
	{
		label: 'Use MDTM to Set Modification Time',
		command: '--ftp-writing-mdtm',
		fieldType: 'bool',
		required: false,
		value: 'writing_mdtm',
		default: false,
		description: 'Use MDTM to set modification time (VsFtpd quirk)',
	},
	{
		label: 'Force Listing of Hidden Files',
		command: '--ftp-force-list-hidden',
		fieldType: 'bool',
		required: false,
		value: 'force_list_hidden',
		default: false,
		description:
			'Use LIST -a to force listing of hidden files and folders. This will disable the use of MLSD.',
	},
	{
		label: 'Idle Connection Timeout',
		command: '--ftp-idle-timeout',
		fieldType: 'duration',
		required: false,
		value: 'idle_timeout',
		default: '1m0s',
		description:
			'Max time before closing idle connections. If no connections are used within this time, the connection pool is emptied.',
	},
	{
		label: 'Close Response Timeout',
		command: '--ftp-close-timeout',
		fieldType: 'duration',
		required: false,
		value: 'close_timeout',
		default: '1m0s',
		description: 'Maximum time to wait for a response to close.',
	},
	{
		label: 'TLS Session Cache Size',
		command: '--ftp-tls-cache-size',
		fieldType: 'int',
		required: false,
		value: 'tls_cache_size',
		default: '32',
		description:
			'Size of TLS session cache for all control and data connections. Enabled by default; use 0 to disable.',
		condition: [{ tls: true }, { explicit_tls: true }],
	},
	{
		label: 'Disable TLS 1.3',
		command: '--ftp-disable-tls13',
		fieldType: 'bool',
		required: false,
		value: 'disable_tls13',
		default: false,
		description: 'Disable TLS 1.3 (workaround for FTP servers with buggy TLS)',
		condition: [{ tls: true }, { explicit_tls: true }],
	},
	{
		label: 'Data Connection Close Timeout',
		command: '--ftp-shut-timeout',
		fieldType: 'duration',
		required: false,
		value: 'shut_timeout',
		default: '1m0s',
		description: 'Maximum time to wait for data connection closing status.',
	},
	{
		label: 'Allow Asking for FTP Password',
		command: '--ftp-ask-password',
		fieldType: 'bool',
		required: false,
		value: 'ask_password',
		default: false,
		description: 'Allow prompting for an FTP password when none is configured.',
	},
	{
		label: 'SOCKS Proxy',
		command: '--ftp-socks-proxy',
		fieldType: 'string',
		required: false,
		value: 'socks_proxy',
		default: '',
		description:
			'Socks 5 proxy host. Supports the format user:pass@host:port, user@host:port, host:port.',
	},
	{
		label: "Don't Check Upload",
		command: '--ftp-no-check-upload',
		fieldType: 'bool',
		required: false,
		value: 'no_check_upload',
		default: false,
		description:
			'Skip verifying uploads. By default, uploaded files are checked to ensure the size and modification time are correct.',
	},
	{
		label: 'Backend Encoding',
		command: '--ftp-encoding',
		fieldType: 'encoding',
		required: false,
		value: 'encoding',
		default: 'slash,del,ctl,rightspace,dot',
		description: 'The encoding for the backend.',
	},
	{
		label: 'Description',
		command: '--ftp-description',
		fieldType: 'string',
		required: false,
		value: 'description',
		default: '',
		description: 'Description of the Storage.',
	},
];

export default ftpSettings;
