const gcsSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id.',
		command: '--gcs-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret.',
		command: '--gcs-client-secret',
	},
	{
		label: 'Project Number',
		value: 'project_number',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			'Project number. Optional - needed only for list/create/delete buckets - see your developer console.',
		command: '--gcs-project-number',
	},
	{
		label: 'User Project',
		value: 'user_project',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'User project. Optional - needed only for requester pays.',
		command: '--gcs-user-project',
	},
	{
		label: 'Service Account File',
		value: 'service_account_file',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Service Account Credentials JSON file path. Leave blank normally. Needed only if you want use SA instead of interactive login.',
		command: '--gcs-service-account-file',
	},
	{
		label: 'Service Account Credentials',
		value: 'service_account_credentials',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Service Account Credentials JSON blob. Leave blank normally. Needed only if you want use SA instead of interactive login.',
		command: '--gcs-service-account-credentials',
	},
	{
		label: 'Anonymous Access',
		value: 'anonymous',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Access public buckets and objects without credentials. Enable if you just want to download files and don't configure credentials.",
		command: '--gcs-anonymous',
	},
	{
		label: 'Object ACL',
		value: 'object_acl',
		fieldType: 'select',
		required: false,
		default: '',
		description: 'Access Control List for new objects.',
		command: '--gcs-object-acl',
		options: [
			{ label: 'Default (private)', value: '' },
			{ label: 'Authenticated Read', value: 'authenticatedRead' },
			{ label: 'Bucket Owner Full Control', value: 'bucketOwnerFullControl' },
			{ label: 'Bucket Owner Read', value: 'bucketOwnerRead' },
			{ label: 'Private', value: 'private' },
			{ label: 'Project Private', value: 'projectPrivate' },
			{ label: 'Public Read', value: 'publicRead' },
		],
	},
	{
		label: 'Bucket ACL',
		value: 'bucket_acl',
		fieldType: 'select',
		required: false,
		default: '',
		description: 'Access Control List for new buckets.',
		command: '--gcs-bucket-acl',
		options: [
			{ label: 'Default (private)', value: '' },
			{ label: 'Authenticated Read', value: 'authenticatedRead' },
			{ label: 'Private', value: 'private' },
			{ label: 'Project Private', value: 'projectPrivate' },
			{ label: 'Public Read', value: 'publicRead' },
			{ label: 'Public Read/Write', value: 'publicReadWrite' },
		],
	},
	{
		label: 'Bucket Policy Only',
		value: 'bucket_policy_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Access checks should use bucket-level IAM policies. If you want to upload objects to a bucket with Bucket Policy Only set then you will need to set this.',
		command: '--gcs-bucket-policy-only',
	},
	{
		label: 'Location',
		value: 'location',
		fieldType: 'select',
		allowCustom: true,
		required: false,
		default: '',
		description: 'Location for the newly created buckets.',
		command: '--gcs-location',
		options: [
			{ label: 'Default (US)', value: '' },
			{ label: 'Multi-regional: Asia', value: 'asia' },
			{ label: 'Multi-regional: EU', value: 'eu' },
			{ label: 'Multi-regional: US', value: 'us' },
			{ label: 'Taiwan', value: 'asia-east1' },
			{ label: 'Hong Kong', value: 'asia-east2' },
			{ label: 'Tokyo', value: 'asia-northeast1' },
			{ label: 'Osaka', value: 'asia-northeast2' },
			{ label: 'Seoul', value: 'asia-northeast3' },
			{ label: 'Mumbai', value: 'asia-south1' },
			{ label: 'Delhi', value: 'asia-south2' },
			{ label: 'Singapore', value: 'asia-southeast1' },
			{ label: 'Jakarta', value: 'asia-southeast2' },
			{ label: 'Sydney', value: 'australia-southeast1' },
			{ label: 'Melbourne', value: 'australia-southeast2' },
			{ label: 'Finland', value: 'europe-north1' },
			{ label: 'Belgium', value: 'europe-west1' },
			{ label: 'London', value: 'europe-west2' },
			{ label: 'Frankfurt', value: 'europe-west3' },
			{ label: 'Netherlands', value: 'europe-west4' },
			{ label: 'Zürich', value: 'europe-west6' },
			{ label: 'Warsaw', value: 'europe-central2' },
			{ label: 'Iowa', value: 'us-central1' },
			{ label: 'South Carolina', value: 'us-east1' },
			{ label: 'Northern Virginia', value: 'us-east4' },
			{ label: 'Oregon', value: 'us-west1' },
			{ label: 'California', value: 'us-west2' },
			{ label: 'Salt Lake City', value: 'us-west3' },
			{ label: 'Las Vegas', value: 'us-west4' },
			{ label: 'Montréal', value: 'northamerica-northeast1' },
			{ label: 'Toronto', value: 'northamerica-northeast2' },
			{ label: 'São Paulo', value: 'southamerica-east1' },
			{ label: 'Santiago', value: 'southamerica-west1' },
			{ label: 'Custom', value: 'custom' },
		],
	},
	{
		label: 'Storage Class',
		value: 'storage_class',
		fieldType: 'select',
		required: false,
		default: '',
		description: 'The storage class to use when storing objects in Google Cloud Storage.',
		command: '--gcs-storage-class',
		options: [
			{ label: 'Default', value: '' },
			{ label: 'Multi-Regional', value: 'MULTI_REGIONAL' },
			{ label: 'Regional', value: 'REGIONAL' },
			{ label: 'Nearline', value: 'NEARLINE' },
			{ label: 'Coldline', value: 'COLDLINE' },
			{ label: 'Archive', value: 'ARCHIVE' },
			{ label: 'Durable Reduced Availability', value: 'DURABLE_REDUCED_AVAILABILITY' },
		],
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Get GCP IAM credentials from runtime (environment variables or instance metadata). Only applies if Service Account File and Service Account Credentials are blank.',
		command: '--gcs-env-auth',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--gcs-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--gcs-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--gcs-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--gcs-client-credentials',
	},
	{
		label: 'Access Token',
		value: 'access_token',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Short-lived access token. Leave blank normally. Needed only if you want use short-lived access token instead of interactive login.',
		command: '--gcs-access-token',
	},
	{
		label: 'Directory Markers',
		value: 'directory_markers',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Upload an empty object with a trailing slash when a new directory is created Empty folders are unsupported for bucket based storages, this option creates an empty object ending with "/", to persist the folder.',
		command: '--gcs-directory-markers',
	},
	{
		label: 'No Check Bucket',
		value: 'no_check_bucket',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"If set, don't attempt to check the bucket exists or create it. Useful if you know the bucket already exists and want to reduce API calls.",
		command: '--gcs-no-check-bucket',
	},
	{
		label: 'Decompress',
		value: 'decompress',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If set, gzip-encoded objects will be decompressed on download.',
		command: '--gcs-decompress',
	},
	{
		label: 'Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Endpoint for the service. Leave blank normally.',
		command: '--gcs-endpoint',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,crlf,invalidutf8,dot',
		description:
			'The encoding for the backend.',
		command: '--gcs-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--gcs-description',
	},
];

export default gcsSettings;
