const gcsSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id.',
		command: '--gcs-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret.',
		command: '--gcs-client-secret',
	},
	{
		label: 'Project Number',
		value: 'project_number',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			'Project number. Optional - needed only for list/create/delete buckets - see your developer console.',
		command: '--gcs-project-number',
	},
	{
		label: 'User Project',
		value: 'user_project',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'User project. Optional - needed only for requester pays.',
		command: '--gcs-user-project',
	},
	{
		label: 'Service Account File',
		value: 'service_account_file',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Service Account Credentials JSON file path. Leave blank normally. Needed only if you want use SA instead of interactive login.',
		command: '--gcs-service-account-file',
	},
	{
		label: 'Service Account Credentials',
		value: 'service_account_credentials',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Service Account Credentials JSON blob. Leave blank normally. Needed only if you want use SA instead of interactive login.',
		command: '--gcs-service-account-credentials',
	},
	{
		label: 'Anonymous Access',
		value: 'anonymous',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Access public buckets and objects without credentials. Enable if you just want to download files and don't configure credentials.",
		command: '--gcs-anonymous',
	},
	{
		label: 'Object ACL',
		value: 'object_acl',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Access Control List for new objects.',
		command: '--gcs-object-acl',
	},
	{
		label: 'Bucket ACL',
		value: 'bucket_acl',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Access Control List for new buckets.',
		command: '--gcs-bucket-acl',
	},
	{
		label: 'Bucket Policy Only',
		value: 'bucket_policy_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Access checks should use bucket-level IAM policies. If you want to upload objects to a bucket with Bucket Policy Only set then you will need to set this.',
		command: '--gcs-bucket-policy-only',
	},
	{
		label: 'Location',
		value: 'location',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Location for the newly created buckets.',
		command: '--gcs-location',
	},
	{
		label: 'Storage Class',
		value: 'storage_class',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The storage class to use when storing objects in Google Cloud Storage.',
		command: '--gcs-storage-class',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Get GCP IAM credentials from runtime (environment variables or instance meta data if no env vars). Only applies if service_account_file and service_account_credentials is blank.',
		command: '--gcs-env-auth',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--gcs-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--gcs-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--gcs-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--gcs-client-credentials',
	},
	{
		label: 'Access Token',
		value: 'access_token',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Short-lived access token. Leave blank normally. Needed only if you want use short-lived access token instead of interactive login.',
		command: '--gcs-access-token',
	},
	{
		label: 'Directory Markers',
		value: 'directory_markers',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Upload an empty object with a trailing slash when a new directory is created Empty folders are unsupported for bucket based storages, this option creates an empty object ending with "/", to persist the folder.',
		command: '--gcs-directory-markers',
	},
	{
		label: 'No Check Bucket',
		value: 'no_check_bucket',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"If set, don't attempt to check the bucket exists or create it. This can be useful when trying to minimise the number of transactions rclone does if you know the bucket exists already.",
		command: '--gcs-no-check-bucket',
	},
	{
		label: 'Decompress',
		value: 'decompress',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If set this will decompress gzip encoded objects. It is possible to upload objects to GCS with "Content-Encoding: gzip" set. Normally rclone will download these files as compressed objects.',
		command: '--gcs-decompress',
	},
	{
		label: 'Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Endpoint for the service. Leave blank normally.',
		command: '--gcs-endpoint',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,crlf,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--gcs-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--gcs-description',
	},
];

export default gcsSettings;
