const googleDriveSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			'Google Application Client ID. Setting your own is recommended for better performance. Leave blank to use the built-in default.',
		command: '--drive-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--drive-client-secret',
	},
	{
		label: 'Scope',
		value: 'scope',
		fieldType: 'select',
		authFieldType: 'all',
		required: true,
		default: 'drive',
		description: 'Access level to request from Google Drive.',
		command: '--drive-scope',
		options: [
			{ label: 'Full access (all files)', value: 'drive' },
			{ label: 'Read-only access', value: 'drive.readonly' },
			{ label: 'Access rclone files only', value: 'drive.file' },
			{ label: 'Application Data folder', value: 'drive.appfolder' },
			{ label: 'Read-only metadata', value: 'drive.metadata.readonly' },
		],
	},
	{
		label: 'Service Account File',
		value: 'service_account_file',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to a Service Account credentials JSON file. Leave blank to use interactive login.',
		command: '--drive-service-account-file',
	},
	{
		label: 'Alternate Export',
		value: 'alternate_export',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Deprecated: No longer needed.',
		command: '--drive-alternate-export',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--drive-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--drive-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--drive-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description: 'Use client credentials OAuth flow instead of interactive login.',
		command: '--drive-client-credentials',
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'ID of the root folder. Leave blank to use the default root. Fill in to access "Computers" folders or start from a specific folder.',
		command: '--drive-root-folder-id',
	},
	{
		label: 'Service Account Credentials',
		value: 'service_account_credentials',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Service Account credentials as a JSON string. Leave blank to use interactive login.',
		command: '--drive-service-account-credentials',
	},
	{
		label: 'Team Drive ID',
		value: 'team_drive',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'ID of the Shared Drive (Team Drive).',
		command: '--drive-team-drive',
	},
	{
		label: 'Auth Owner Only',
		value: 'auth_owner_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Only consider files owned by the authenticated user.',
		command: '--drive-auth-owner-only',
	},
	{
		label: 'Use Trash',
		value: 'use_trash',
		fieldType: 'bool',
		required: false,
		default: true,
		description: 'Send files to the trash instead of deleting permanently.',
		command: '--drive-use-trash',
	},
	{
		label: 'Copy Shortcut Content',
		value: 'copy_shortcut_content',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Copy the actual file contents of shortcuts instead of the shortcut itself.',
		command: '--drive-copy-shortcut-content',
	},
	{
		label: 'Skip Google Docs',
		value: 'skip_gdocs',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Skip Google Docs in all file listings, making them invisible.',
		command: '--drive-skip-gdocs',
	},
	{
		label: 'Show All Google Docs',
		value: 'show_all_gdocs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Show all Google Docs in listings, including non-exportable ones like Google Forms.',
		command: '--drive-show-all-gdocs',
	},
	{
		label: 'Skip Checksum GPhotos',
		value: 'skip_checksum_gphotos',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Skip checksums on Google photos and videos only. Use this if you get checksum errors when transferring Google photos or videos.',
		command: '--drive-skip-checksum-gphotos',
	},
	{
		label: 'Shared With Me',
		value: 'shared_with_me',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Only show files from your "Shared with me" folder.',
		command: '--drive-shared-with-me',
	},
	{
		label: 'Trashed Only',
		value: 'trashed_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Only show files that are in the trash. This will show trashed files in their original directory structure.',
		command: '--drive-trashed-only',
	},
	{
		label: 'Starred Only',
		value: 'starred_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Only show files that are starred.',
		command: '--drive-starred-only',
	},
	{
		label: 'Formats',
		value: 'formats',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Deprecated: See Export Formats.',
		command: '--drive-formats',
	},
	{
		label: 'Export Formats',
		value: 'export_formats',
		fieldType: 'string',
		required: false,
		default: 'docx,xlsx,pptx,svg',
		description: 'Comma separated list of preferred formats for downloading Google docs.',
		command: '--drive-export-formats',
	},
	{
		label: 'Import Formats',
		value: 'import_formats',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Comma separated list of preferred formats for uploading Google docs.',
		command: '--drive-import-formats',
	},
	{
		label: 'Allow Import Name Change',
		value: 'allow_import_name_change',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Allow the file type to change when uploading Google Docs (e.g., file.doc to file.docx). This may cause files to be re-uploaded on each sync.',
		command: '--drive-allow-import-name-change',
	},
	{
		label: 'Use Created Date',
		value: 'use_created_date',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Use the file creation date instead of the last modified date.',
		command: '--drive-use-created-date',
	},
	{
		label: 'Use Shared Date',
		value: 'use_shared_date',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use the date a file was shared instead of the last modified date. Like "Use Created Date", this may cause unexpected behavior during transfers.',
		command: '--drive-use-shared-date',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '1000',
		description: 'Size of listing chunk 100-1000, 0 to disable.',
		command: '--drive-list-chunk',
	},
	{
		label: 'Impersonate',
		value: 'impersonate',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Impersonate this user when using a service account.',
		command: '--drive-impersonate',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '8mi',
		description: 'Cutoff for switching to chunked upload.',
		command: '--drive-upload-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '8mi',
		description: 'Upload chunk size. Must a power of 2 >= 256k.',
		command: '--drive-chunk-size',
	},
	{
		label: 'Acknowledge Abuse',
		value: 'acknowledge_abuse',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Allow downloading files that Google has flagged as potential malware or spam.',
		command: '--drive-acknowledge-abuse',
	},
	{
		label: 'Keep Revision Forever',
		value: 'keep_revision_forever',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Keep new head revision of each file forever.',
		command: '--drive-keep-revision-forever',
	},
	{
		label: 'Size As Quota',
		value: 'size_as_quota',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Show file sizes as storage quota usage (including all kept versions) instead of the actual file size.',
		command: '--drive-size-as-quota',
	},
	{
		label: 'V2 Download Min Size',
		value: 'v2_download_min_size',
		fieldType: 'sizesuffix',
		required: false,
		default: 'off',
		description:
			'Minimum file size to trigger an alternative download method. Leave as default unless experiencing issues with large files.',
		command: '--drive-v2-download-min-size',
	},
	{
		label: 'Pacer Min Sleep',
		value: 'pacer_min_sleep',
		fieldType: 'duration',
		required: false,
		default: '100ms',
		description: 'Minimum time to sleep between API calls.',
		command: '--drive-pacer-min-sleep',
	},
	{
		label: 'Pacer Burst',
		value: 'pacer_burst',
		fieldType: 'int',
		required: false,
		default: '100',
		description: 'Number of API calls to allow without sleeping.',
		command: '--drive-pacer-burst',
	},
	{
		label: 'Server Side Across Configs',
		value: 'server_side_across_configs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Deprecated. Allow server-side operations (e.g., copy) to work across different Google Drive configurations.',
		command: '--drive-server-side-across-configs',
	},
	{
		label: 'Disable HTTP2',
		value: 'disable_http2',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Disable HTTP/2 for Google Drive connections. Disabled by default due to a known issue.',
		command: '--drive-disable-http2',
	},
	{
		label: 'Stop On Upload Limit',
		value: 'stop_on_upload_limit',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Stop the operation when Google Drive's daily upload limit (approximately 750 GB/day) is reached.",
		command: '--drive-stop-on-upload-limit',
	},
	{
		label: 'Stop On Download Limit',
		value: 'stop_on_download_limit',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Stop the operation when Google Drive's daily download limit (approximately 10 TB/day) is reached.",
		command: '--drive-stop-on-download-limit',
	},
	{
		label: 'Skip Shortcuts',
		value: 'skip_shortcuts',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Skip shortcut files instead of following them to the original file.',
		command: '--drive-skip-shortcuts',
	},
	{
		label: 'Skip Dangling Shortcuts',
		value: 'skip_dangling_shortcuts',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Skip shortcut files that point to deleted or inaccessible files.',
		command: '--drive-skip-dangling-shortcuts',
	},
	{
		label: 'Resource Key',
		value: 'resource_key',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Resource key for accessing a link-shared file.',
		command: '--drive-resource-key',
	},
	{
		label: 'Fast List Bug Fix',
		value: 'fast_list_bug_fix',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Work around a bug in Google Drive that can cause some files to be missed in listings.',
		command: '--drive-fast-list-bug-fix',
	},
	{
		label: 'Metadata Owner',
		value: 'metadata_owner',
		fieldType: 'bits',
		required: false,
		default: 'read',
		description:
			'Control whether file ownership information should be read or written in metadata.',
		command: '--drive-metadata-owner',
	},
	{
		label: 'Metadata Permissions',
		value: 'metadata_permissions',
		fieldType: 'bits',
		required: false,
		default: 'off',
		description:
			'Control whether file permissions should be read or written in metadata.',
		command: '--drive-metadata-permissions',
	},
	{
		label: 'Metadata Labels',
		value: 'metadata_labels',
		fieldType: 'bits',
		required: false,
		default: 'off',
		description:
			'Control whether labels should be read or written in metadata. Reading labels will slow down file listings.',
		command: '--drive-metadata-labels',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'invalidutf8',
		description: 'Character encoding for file and folder names.',
		command: '--drive-encoding',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Get IAM credentials from the environment. Only applies if Service Account File and Service Account Credentials are blank.',
		command: '--drive-env-auth',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--drive-description',
	},
];

export default googleDriveSettings;
