const googleDriveSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			'Google Application Client Id Setting your own is recommended. See https://rclone.org/drive/#making-your-own-client-id for how to create your own. If you leave this blank, it will use an internal key which is low performance.',
		command: '--drive-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--drive-client-secret',
	},
	{
		label: 'Scope',
		value: 'scope',
		fieldType: 'string',
		authFieldType: 'all',
		required: true,
		default: '',
		description:
			'Comma separated list of scopes that rclone should use when requesting access from drive. Scopes: drive.readonly, drive.file, drive.appfolder, drive.metadata.readonly',
		command: '--drive-scope',
	},
	{
		label: 'Service Account File',
		value: 'service_account_file',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Service Account Credentials JSON file path. Leave blank normally. Needed only if you want use SA instead of interactive login.',
		command: '--drive-service-account-file',
	},
	{
		label: 'Alternate Export',
		value: 'alternate_export',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Deprecated: No longer needed.',
		command: '--drive-alternate-export',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--drive-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--drive-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--drive-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--drive-client-credentials',
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'ID of the root folder. Leave blank normally. Fill in to access "Computers" folders (see docs), or for rclone to use a non root folder as its starting point.',
		command: '--drive-root-folder-id',
	},
	{
		label: 'Service Account Credentials',
		value: 'service_account_credentials',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Service Account Credentials JSON blob. Leave blank normally. Needed only if you want use SA instead of interactive login.',
		command: '--drive-service-account-credentials',
	},
	{
		label: 'Team Drive ID',
		value: 'team_drive',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'ID of the Shared Drive (Team Drive).',
		command: '--drive-team-drive',
	},
	{
		label: 'Auth Owner Only',
		value: 'auth_owner_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Only consider files owned by the authenticated user.',
		command: '--drive-auth-owner-only',
	},
	{
		label: 'Use Trash',
		value: 'use_trash',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Send files to the trash instead of deleting permanently. Defaults to true, namely sending files to the trash. Use --drive-use-trash=false to delete files permanently instead.',
		command: '--drive-use-trash',
	},
	{
		label: 'Copy Shortcut Content',
		value: 'copy_shortcut_content',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Server side copy contents of shortcuts instead of the shortcut. When doing server side copies, normally rclone will copy shortcuts as shortcuts.',
		command: '--drive-copy-shortcut-content',
	},
	{
		label: 'Skip Google Docs',
		value: 'skip_gdocs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Skip google documents in all listings. If given, gdocs practically become invisible to rclone.',
		command: '--drive-skip-gdocs',
	},
	{
		label: 'Show All Google Docs',
		value: 'show_all_gdocs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Show all Google Docs including non-exportable ones in listings. If you try a server side copy on a Google Form without this flag, you will get this error:',
		command: '--drive-show-all-gdocs',
	},
	{
		label: 'Skip Checksum GPhotos',
		value: 'skip_checksum_gphotos',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Skip checksums on Google photos and videos only. Use this if you get checksum errors when transferring Google photos or videos.',
		command: '--drive-skip-checksum-gphotos',
	},
	{
		label: 'Shared With Me',
		value: 'shared_with_me',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Only show files that are shared with me. Instructs rclone to operate on your "Shared with me" folder (where Google Drive lets you access the files and folders others have shared with you).',
		command: '--drive-shared-with-me',
	},
	{
		label: 'Trashed Only',
		value: 'trashed_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Only show files that are in the trash. This will show trashed files in their original directory structure.',
		command: '--drive-trashed-only',
	},
	{
		label: 'Starred Only',
		value: 'starred_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Only show files that are starred.',
		command: '--drive-starred-only',
	},
	{
		label: 'Formats',
		value: 'formats',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Deprecated: See export_formats.',
		command: '--drive-formats',
	},
	{
		label: 'Export Formats',
		value: 'export_formats',
		fieldType: 'string',
		required: false,
		default: 'docx,xlsx,pptx,svg',
		description: 'Comma separated list of preferred formats for downloading Google docs.',
		command: '--drive-export-formats',
	},
	{
		label: 'Import Formats',
		value: 'import_formats',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Comma separated list of preferred formats for uploading Google docs.',
		command: '--drive-import-formats',
	},
	{
		label: 'Allow Import Name Change',
		value: 'allow_import_name_change',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Allow the filetype to change when uploading Google docs. E.g. file.doc to file.docx. This will confuse sync and reupload every time.',
		command: '--drive-allow-import-name-change',
	},
	{
		label: 'Use Created Date',
		value: 'use_created_date',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use file created date instead of modified date. Useful when downloading data and you want the creation date used in place of the last modified date.',
		command: '--drive-use-created-date',
	},
	{
		label: 'Use Shared Date',
		value: 'use_shared_date',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use date file was shared instead of modified date. Note that, as with "--drive-use-created-date", this flag may have unexpected consequences when uploading/downloading files.',
		command: '--drive-use-shared-date',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '1000',
		description: 'Size of listing chunk 100-1000, 0 to disable.',
		command: '--drive-list-chunk',
	},
	{
		label: 'Impersonate',
		value: 'impersonate',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Impersonate this user when using a service account.',
		command: '--drive-impersonate',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '8mi',
		description: 'Cutoff for switching to chunked upload.',
		command: '--drive-upload-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '8mi',
		description: 'Upload chunk size. Must a power of 2 >= 256k.',
		command: '--drive-chunk-size',
	},
	{
		label: 'Acknowledge Abuse',
		value: 'acknowledge_abuse',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Set to allow files which return cannotDownloadAbusiveFile to be downloaded. If downloading a file returns the error "This file has been identified as malware or spam and cannot be downloaded" with the error code "cannotDownloadAbusiveFile" then supply this flag to rclone to indicate you acknowledge the risks of downloading the file and rclone will download it anyway.',
		command: '--drive-acknowledge-abuse',
	},
	{
		label: 'Keep Revision Forever',
		value: 'keep_revision_forever',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Keep new head revision of each file forever.',
		command: '--drive-keep-revision-forever',
	},
	{
		label: 'Size As Quota',
		value: 'size_as_quota',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Show sizes as storage quota usage, not actual size. Show the size of a file as the storage quota used. This is the current version plus any older versions that have been set to keep forever.',
		command: '--drive-size-as-quota',
	},
	{
		label: 'V2 Download Min Size',
		value: 'v2_download_min_size',
		fieldType: 'sizesuffix',
		required: false,
		default: 'off',
		description: "If Object's are greater, use drive v2 API to download.",
		command: '--drive-v2-download-min-size',
	},
	{
		label: 'Pacer Min Sleep',
		value: 'pacer_min_sleep',
		fieldType: 'duration',
		required: false,
		default: '100ms',
		description: 'Minimum time to sleep between API calls.',
		command: '--drive-pacer-min-sleep',
	},
	{
		label: 'Pacer Burst',
		value: 'pacer_burst',
		fieldType: 'int',
		required: false,
		default: '100',
		description: 'Number of API calls to allow without sleeping.',
		command: '--drive-pacer-burst',
	},
	{
		label: 'Server Side Across Configs',
		value: 'server_side_across_configs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Deprecated: use --server-side-across-configs instead. Allow server-side operations (e.g. copy) to work across different drive configs.',
		command: '--drive-server-side-across-configs',
	},
	{
		label: 'Disable HTTP2',
		value: 'disable_http2',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Disable drive using http2. There is currently an unsolved issue with the google drive backend and HTTP/2.  HTTP/2 is therefore disabled by default for the drive backend but can be re-enabled here.  When the issue is solved this flag will be removed.',
		command: '--drive-disable-http2',
	},
	{
		label: 'Stop On Upload Limit',
		value: 'stop_on_upload_limit',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Make upload limit errors be fatal. At the time of writing it is only possible to upload 750 GiB of data to Google Drive a day (this is an undocumented limit). When this limit is reached Google Drive produces a slightly different error message. When this flag is set it causes these errors to be fatal.  These will stop the in-progress sync.',
		command: '--drive-stop-on-upload-limit',
	},
	{
		label: 'Stop On Download Limit',
		value: 'stop_on_download_limit',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Make download limit errors be fatal. At the time of writing it is only possible to download 10 TiB of data from Google Drive a day (this is an undocumented limit). When this limit is reached Google Drive produces a slightly different error message. When this flag is set it causes these errors to be fatal.  These will stop the in-progress sync.',
		command: '--drive-stop-on-download-limit',
	},
	{
		label: 'Skip Shortcuts',
		value: 'skip_shortcuts',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If set skip shortcut files. Normally rclone dereferences shortcut files making them appear as if they are the original file (see the shortcuts section). If this flag is set then rclone will ignore shortcut files completely.',
		command: '--drive-skip-shortcuts',
	},
	{
		label: 'Skip Dangling Shortcuts',
		value: 'skip_dangling_shortcuts',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If set skip dangling shortcut files. If this is set then rclone will not show any dangling shortcuts in listings.',
		command: '--drive-skip-dangling-shortcuts',
	},
	{
		label: 'Resource Key',
		value: 'resource_key',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Resource key for accessing a link-shared file. If you need to access files shared with a link like this',
		command: '--drive-resource-key',
	},
	{
		label: 'Fast List Bug Fix',
		value: 'fast_list_bug_fix',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Work around a bug in Google Drive listing. Normally rclone will work around a bug in Google Drive when using --fast-list (ListR) where the search "(A in parents) or (B in parents)" returns nothing sometimes. See #3114, #4289 and https://issuetracker.google.com/issues/149522397',
		command: '--drive-fast-list-bug-fix',
	},
	{
		label: 'Metadata Owner',
		value: 'metadata_owner',
		fieldType: 'bits',
		required: false,
		default: 'read',
		description:
			"Control whether owner should be read or written in metadata. Owner is a standard part of the file metadata so is easy to read. But it isn't always desirable to set the owner from the metadata.",
		command: '--drive-metadata-owner',
	},
	{
		label: 'Metadata Permissions',
		value: 'metadata_permissions',
		fieldType: 'bits',
		required: false,
		default: 'off',
		description:
			"Control whether permissions should be read or written in metadata. Reading permissions metadata from files can be done quickly, but it isn't always desirable to set the permissions from the metadata.",
		command: '--drive-metadata-permissions',
	},
	{
		label: 'Metadata Labels',
		value: 'metadata_labels',
		fieldType: 'bits',
		required: false,
		default: 'off',
		description:
			"Control whether labels should be read or written in metadata. Reading labels metadata from files takes an extra API transaction and will slow down listings. It isn't always desirable to set the labels from the metadata.",
		command: '--drive-metadata-labels',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'invalidutf8',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--drive-encoding',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Get IAM credentials from runtime (environment variables or instance meta data if no env vars). Only applies if service_account_file and service_account_credentials is blank.',
		command: '--drive-env-auth',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--drive-description',
	},
];

export default googleDriveSettings;
