const gphotosSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--gphotos-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--gphotos-client-secret',
	},
	{
		label: 'Read Only Access',
		value: 'read_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Set to make the Google Photos backend read only. If you choose read only then rclone will only request read only access to your photos, otherwise rclone will request full access.',
		command: '--gphotos-read-only',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--gphotos-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--gphotos-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--gphotos-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--gphotos-client-credentials',
	},
	{
		label: 'Read Size',
		value: 'read_size',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Set to read the size of media items. Normally rclone does not read the size of media items since this takes another transaction.  This isn't necessary for syncing.  However rclone mount needs to know the size of files in advance of reading them, so setting this flag when using rclone mount is recommended if you want to read the media.",
		command: '--gphotos-read-size',
	},
	{
		label: 'Start Year',
		value: 'start_year',
		fieldType: 'int',
		required: false,
		default: '2000',
		description:
			'Year limits the photos to be downloaded to those which are uploaded after the given year.',
		command: '--gphotos-start-year',
	},
	{
		label: 'Include Archived',
		value: 'include_archived',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Also view and download archived media. By default, rclone does not request archived media. Thus, when syncing, archived media is not visible in directory listings or transferred.',
		command: '--gphotos-include-archived',
	},
	{
		label: 'Proxy',
		value: 'proxy',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"Use the gphotosdl proxy for downloading the full resolution images The Google API will deliver images and video which aren't full resolution, and/or have EXIF data missing.",
		command: '--gphotos-proxy',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,crlf,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--gphotos-encoding',
	},
	{
		label: 'Batch Mode',
		value: 'batch_mode',
		fieldType: 'string',
		required: false,
		default: 'sync',
		description: 'Upload file batching sync|async|off. This sets the batch mode used by rclone.',
		command: '--gphotos-batch-mode',
	},
	{
		label: 'Batch Size',
		value: 'batch_size',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'Max number of files in upload batch. This sets the batch size of files to upload. It has to be less than 50.',
		command: '--gphotos-batch-size',
	},
	{
		label: 'Batch Timeout',
		value: 'batch_timeout',
		fieldType: 'duration',
		required: false,
		default: '0s',
		description:
			'Max time to allow an idle upload batch before uploading. If an upload batch is idle for more than this long then it will be uploaded.',
		command: '--gphotos-batch-timeout',
	},
	{
		label: 'Batch Commit Timeout',
		value: 'batch_commit_timeout',
		fieldType: 'duration',
		required: false,
		default: '10m0s',
		description: 'Max time to wait for a batch to finish committing',
		command: '--gphotos-batch-commit-timeout',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--gphotos-description',
	},
];

export default gphotosSettings;
