const gphotosSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--gphotos-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--gphotos-client-secret',
	},
	{
		label: 'Read Only Access',
		value: 'read_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Set to read-only access. When enabled, only viewing and downloading photos is allowed.',
		command: '--gphotos-read-only',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--gphotos-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--gphotos-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--gphotos-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description: 'Use client credentials OAuth flow instead of interactive login.',
		command: '--gphotos-client-credentials',
	},
	{
		label: 'Read Size',
		value: 'read_size',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Read the size of media items. This adds an extra request per file but may be needed for some advanced operations.',
		command: '--gphotos-read-size',
	},
	{
		label: 'Start Year',
		value: 'start_year',
		fieldType: 'int',
		required: false,
		default: '2000',
		description:
			'Year limits the photos to be downloaded to those which are uploaded after the given year.',
		command: '--gphotos-start-year',
	},
	{
		label: 'Include Archived',
		value: 'include_archived',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Also view and download archived media. By default, archived media is hidden from listings and not transferred.',
		command: '--gphotos-include-archived',
	},
	{
		label: 'Proxy',
		value: 'proxy',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Proxy URL for downloading full-resolution images. Without this, Google may deliver lower-resolution images with missing EXIF data.',
		command: '--gphotos-proxy',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,crlf,invalidutf8,dot',
		description: 'Character encoding for file and folder names.',
		command: '--gphotos-encoding',
	},
	{
		label: 'Batch Mode',
		value: 'batch_mode',
		fieldType: 'select',
		required: false,
		default: 'sync',
		description: 'Upload file batching mode.',
		command: '--gphotos-batch-mode',
		options: [
			{ label: 'Sync (batch and check completion)', value: 'sync' },
			{ label: 'Async (batch, no completion check)', value: 'async' },
			{ label: 'Off (no batching)', value: 'off' },
		],
	},
	{
		label: 'Batch Size',
		value: 'batch_size',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'Max number of files in upload batch. This sets the batch size of files to upload. It has to be less than 50.',
		command: '--gphotos-batch-size',
	},
	{
		label: 'Batch Timeout',
		value: 'batch_timeout',
		fieldType: 'duration',
		required: false,
		default: '0s',
		description:
			'Max time to allow an idle upload batch before uploading. If an upload batch is idle for more than this long then it will be uploaded.',
		command: '--gphotos-batch-timeout',
	},
	{
		label: 'Batch Commit Timeout',
		value: 'batch_commit_timeout',
		fieldType: 'duration',
		required: false,
		default: '10m0s',
		description: 'Max time to wait for a batch to finish committing',
		command: '--gphotos-batch-commit-timeout',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--gphotos-description',
	},
];

export default gphotosSettings;
