const hidriveSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--hidrive-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--hidrive-client-secret',
	},
	{
		label: 'Access Scope',
		value: 'scope_access',
		fieldType: 'string',
		required: false,
		default: 'rw',
		description:
			'Access permissions to use when requesting access from HiDrive. rw: Read/Write, ro: Read-only',
		command: '--hidrive-scope-access',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--hidrive-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--hidrive-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--hidrive-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--hidrive-client-credentials',
	},
	{
		label: 'Role Scope',
		value: 'scope_role',
		fieldType: 'string',
		required: false,
		default: 'user',
		description: 'User-level that rclone should use when requesting access from HiDrive.',
		command: '--hidrive-scope-role',
	},
	{
		label: 'Root Prefix',
		value: 'root_prefix',
		fieldType: 'string',
		required: false,
		default: '/',
		description:
			'The root/parent folder for all paths. Fill in to use the specified folder as the parent for all paths given to the storage. This way rclone can use any folder as its starting point.',
		command: '--hidrive-root-prefix',
	},
	{
		label: 'Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: 'https://api.hidrive.strato.com/2.1',
		description: 'Endpoint for the service. This is the URL that API-calls will be made to.',
		command: '--hidrive-endpoint',
	},
	{
		label: 'Disable Member Count',
		value: 'disable_fetching_member_count',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Do not fetch number of objects in directories unless it is absolutely necessary. Requests may be faster if the number of objects in subdirectories is not fetched.',
		command: '--hidrive-disable-fetching-member-count',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '48mi',
		description:
			'Chunksize for chunked uploads. Any files larger than the configured cutoff (or files of unknown size) will be uploaded in chunks of this size.',
		command: '--hidrive-chunk-size',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '96mi',
		description:
			'Cutoff/Threshold for chunked uploads. Any files larger than this will be uploaded in chunks of the configured chunksize.',
		command: '--hidrive-upload-cutoff',
	},
	{
		label: 'Upload Concurrency',
		value: 'upload_concurrency',
		fieldType: 'int',
		required: false,
		default: '4',
		description:
			'Concurrency for chunked uploads. This is the upper limit for how many transfers for the same file are running concurrently. Setting this above to a value smaller than 1 will cause uploads to deadlock.',
		command: '--hidrive-upload-concurrency',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--hidrive-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--hidrive-description',
	},
];

export default hidriveSettings;
