const jottacloudSettings = [
	{
		label: 'Login Token',
		value: 'login_token',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'Personal login token. Generate here: https://www.jottacloud.com/web/secure',
		command: '--jottacloud-login-token',
	},
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--jottacloud-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--jottacloud-client-secret',
	},
	{
		label: 'OAuth Token',
		value: 'token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--jottacloud-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--jottacloud-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--jottacloud-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--jottacloud-client-credentials',
	},
	{
		label: 'MD5 Memory Limit',
		value: 'md5_memory_limit',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description: 'Files bigger than this will be cached on disk to calculate the MD5 if required.',
		command: '--jottacloud-md5-memory-limit',
	},
	{
		label: 'Trashed Only',
		value: 'trashed_only',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Only show files that are in the trash. This will show trashed files in their original directory structure.',
		command: '--jottacloud-trashed-only',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Delete files permanently rather than putting them into the trash.',
		command: '--jottacloud-hard-delete',
	},
	{
		label: 'Upload Resume Limit',
		value: 'upload_resume_limit',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description: "Files bigger than this can be resumed if the upload fail's.",
		command: '--jottacloud-upload-resume-limit',
	},
	{
		label: 'No Versions',
		value: 'no_versions',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Avoid server side versioning by deleting files and recreating files instead of overwriting them.',
		command: '--jottacloud-no-versions',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,ltgt,doublequote,colon,question,asterisk,pipe,del,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--jottacloud-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--jottacloud-description',
	},
];

export default jottacloudSettings;
