import s3Options from './_s3Options';

const linodeSettings = [
	{
		label: 'Access Key ID',
		value: 'access_key_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Access Key ID.',
		command: '--s3-access-key-id',
	},
	{
		label: 'Secret Access Key',
		value: 'secret_access_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Secret Access Key (password).',
		command: '--s3-secret-access-key',
	},
	{
		label: 'Region',
		value: 'ednpoint',
		fieldType: 'select',
		authFieldType: 'client',
		allowCustom: true,
		options: [
			{ label: 'Select Region', value: '' },
			{ label: 'Atlanta, GA, United States', value: 'us-southeast-1.linodeobjects.com' },
			{ label: 'Chicago, IL, United States', value: 'us-ord-1.linodeobjects.com' },
			{ label: 'Los Angeles, CA, United States', value: 'us-lax-1.linodeobjects.com' },
			{ label: 'Miami, FL, United States', value: 'us-mia-1.linodeobjects.com' },
			{ label: 'Newark, NJ, United States', value: 'us-east-1.linodeobjects.com' },
			{ label: 'Seattle, WA, United States', value: 'us-sea-1.linodeobjects.com' },
			{ label: 'Seattle, WA, United States', value: 'us-sea-9.linodeobjects.com' },
			{ label: 'Washington, DC, United States', value: 'us-iad-1.linodeobjects.com' },
			{ label: 'Washington, DC, United States', value: 'us-iad-10.linodeobjects.com' },
			{ label: 'Jakarta, Indonesia', value: 'id-cgk-1.linodeobjects.com' },
			{ label: 'Chennai, India', value: 'in-maa-1.linodeobjects.com' },
			{ label: 'Mumbai 2, India', value: 'in-bom-1.linodeobjects.com' },
			{ label: 'Osaka, Japan', value: 'jp-osa-1.linodeobjects.com' },
			{ label: 'Singapore, Singapore', value: 'ap-south-1.linodeobjects.com' },
			{ label: 'Singapore 2, Singapore', value: 'sg-sin-1.linodeobjects.com' },
			{ label: 'Frankfurt, Germany', value: 'eu-central-1.linodeobjects.com' },
			{ label: 'Frankfurt 2, Germany', value: 'de-fra-1.linodeobjects.com' },
			{ label: 'Madrid, Spain', value: 'es-mad-1.linodeobjects.com' },
			{ label: 'Paris, France', value: 'fr-par-1.linodeobjects.com' },
			{ label: 'London 2, Great Britain', value: 'gb-lon-1.linodeobjects.com' },
			{ label: 'Milan, Italy', value: 'it-mil-1.linodeobjects.com' },
			{ label: 'Amsterdam, Netherlands', value: 'nl-ams-1.linodeobjects.com' },
			{ label: 'Stockholm, Sweden', value: 'se-sto-1.linodeobjects.com' },
			{ label: 'Melbourne, Australia', value: 'au-mel-1.linodeobjects.com' },
			{ label: 'São Paulo, Brazil', value: 'br-gru-1.linodeobjects.com' },
			{ label: 'Insert Custon Endpoint', value: 'custom' },
		],
		required: true,
		default: '',
		description:
			"Select a Region to connect to that region's API Ednpoint. Custom Endpoint example: au-mel-1.linodeobjects.com",
		command: '--s3-region',
	},
	...s3Options,
];

export default linodeSettings;
