const mailruSettings = [
	{
		label: 'User Name',
		value: 'user',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'User name (usually email).',
		command: '--mailru-user',
	},
	{
		label: 'App Password',
		value: 'pass',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			'This must be an app password. Regular passwords are not supported. See your Mail.ru account settings to create an app password.',
		command: '--mailru-pass',
	},
	{
		label: 'OAuth Client ID',
		value: 'client_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--mailru-client-id',
	},
	{
		label: 'OAuth Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--mailru-client-secret',
	},
	{
		label: 'Speedup Enable',
		value: 'speedup_enable',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Skip full upload if another file with the same data hash already exists. Especially efficient for common files like popular media. Not effective for unique or encrypted files.',
		command: '--mailru-speedup-enable',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		required: false,
		authFieldType: 'oauth',
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--mailru-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--mailru-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--mailru-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--mailru-client-credentials',
	},
	{
		label: 'Speedup File Patterns',
		value: 'speedup_file_patterns',
		fieldType: 'string',
		required: false,
		default: '.mkv,.avi,.mp4,.mp3,.zip,.gz,.rar,.pdf',
		description:
			"Comma separated list of file name patterns eligible for speedup (put by hash). Patterns are case insensitive and can contain '*' or '?' meta characters.",
		command: '--mailru-speedup-file-patterns',
	},
	{
		label: 'Speedup Max Disk',
		value: 'speedup_max_disk',
		fieldType: 'sizesuffix',
		required: false,
		default: '3gi',
		description:
			'This option allows you to disable speedup (put by hash) for large files. Reason is that preliminary hashing can exhaust your RAM or disk space.',
		command: '--mailru-speedup-max-disk',
	},
	{
		label: 'Speedup Max Memory',
		value: 'speedup_max_memory',
		fieldType: 'sizesuffix',
		required: false,
		default: '32mi',
		description: 'Files larger than the size given below will always be hashed on disk.',
		command: '--mailru-speedup-max-memory',
	},
	{
		label: 'Check Hash',
		value: 'check_hash',
		fieldType: 'bool',
		required: false,
		default: true,
		description: 'What should copy do if file checksum is mismatched or invalid.',
		command: '--mailru-check-hash',
	},
	{
		label: 'User Agent',
		value: 'user_agent',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'HTTP user agent used internally by the client.',
		command: '--mailru-user-agent',
	},
	{
		label: 'Quirks',
		value: 'quirks',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Comma separated list of internal maintenance flags. Used for troubleshooting backend issues.',
		command: '--mailru-quirks',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default:
			'slash,ltgt,doublequote,colon,question,asterisk,pipe,backslash,del,ctl,invalidutf8,dot',
		description: 'The encoding for the backend.',
		command: '--mailru-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--mailru-description',
	},
];

export default mailruSettings;
