import s3Options from './_s3Options';

const obsSettings = [
	{
		label: 'Access Key ID',
		value: 'access_key_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Your Access Key ID.',
		command: '--s3-access-key-id',
	},
	{
		label: 'Secret Access Key',
		value: 'secret_access_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Your Secret Access Key (password).',
		command: '--s3-secret-access-key',
	},
	{
		label: 'Region',
		value: 'endpoint',
		fieldType: 'select',
		authFieldType: 'client',
		allowCustom: true,
		options: [
			{ label: 'Select Region', value: '' },
			{ label: 'AF-Johannesburg', value: 'af-south-1' },
			{ label: 'CN-Hong Kong', value: 'ap-southeast-1' },
			{ label: 'AP-Bangkok', value: 'ap-southeast-2' },
			{ label: 'AP-Singapore', value: 'ap-southeast-3' },
			{ label: 'AP-Jakarta', value: 'ap-southeast-4' },
			{ label: 'CN East-Shanghai2', value: 'cn-east-2' },
			{ label: 'CN East-Shanghai1', value: 'cn-east-3' },
			{ label: 'CN North-Beijing1', value: 'cn-north-1' },
			{ label: 'CN North-Beijing4', value: 'cn-north-4' },
			{ label: 'CN North-Ulanqab1', value: 'cn-north-9' },
			{ label: 'CN South-Guangzhou', value: 'cn-south-1' },
			{ label: 'CN South-Shenzhen', value: 'cn-south-2' },
			{ label: 'CN South-Guangzhou-InvitationOnly', value: 'cn-south-4' },
			{ label: 'CN Southwest-Guiyang1', value: 'cn-southwest-2' },
			{ label: 'LA-Mexico City2', value: 'la-north-2' },
			{ label: 'LA-Santiago', value: 'la-south-2' },
			{ label: 'LA-Mexico City1', value: 'na-mexico-1' },
			{ label: 'LA-Sao Paulo1', value: 'sa-brazil-1' },
			{ label: 'TR-Istanbul', value: 'tr-west-1' },
			{ label: 'Insert Custon Endpoint', value: 'custom' },
		],
		required: true,
		default: '',
		description: "Select a Region to connect to that region's API Endpoint.",
		command: '--s3-region',
	},
	...s3Options,
];

export default obsSettings;
