const onedriveSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--onedrive-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--onedrive-client-secret',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'select',
		authFieldType: 'client',
		required: false,
		default: 'global',
		options: [
			{ label: 'Microsoft Cloud Global', value: 'global' },
			{ label: 'Microsoft Cloud for US Government', value: 'us' },
			{ label: 'Microsoft Cloud Germany', value: 'de' },
			{ label: 'Azure and Office 365 operated by Vnet Group in China', value: 'cn' },
		],
		description: 'Choose national cloud region for OneDrive.',
		command: '--onedrive-region',
	},
	{
		label: 'Tenant ID',
		value: 'tenant',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			"ID of the service principal's tenant. Also called its directory ID. Set this if using",
		command: '--onedrive-tenant',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--onedrive-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--onedrive-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--onedrive-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--onedrive-client-credentials',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description:
			'Chunk size to upload files with - must be multiple of 320k (327,680 bytes). Above this size files will be chunked - must be multiple of 320k (327,680 bytes) and should not exceed 250M (262,144,000 bytes) else you may encounter "Microsoft.SharePoint.Client.InvalidClientQueryException: The request message is too big." Note that the chunks will be buffered into memory.',
		command: '--onedrive-chunk-size',
	},
	{
		label: 'Drive ID',
		value: 'drive_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The ID of the drive to use.',
		command: '--onedrive-drive-id',
	},
	{
		label: 'Drive Type',
		value: 'drive_type',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The type of the drive (personal | business | documentLibrary).',
		command: '--onedrive-drive-type',
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"ID of the root folder. This isn't normally needed, but in special circumstances you might know the folder ID that you wish to access but not be able to get there through a path traversal.",
		command: '--onedrive-root-folder-id',
	},
	{
		label: 'Access Scopes',
		value: 'access_scopes',
		fieldType: 'spaceseplist',
		required: false,
		default:
			'files.read files.readwrite files.read.all files.readwrite.all sites.read.all offline_access',
		description:
			'Set scopes to be requested by rclone. Choose or manually enter a custom space separated list with all scopes, that rclone should request.',
		command: '--onedrive-access-scopes',
	},
	{
		label: 'Disable Site Permission',
		value: 'disable_site_permission',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Disable the request for Sites.Read.All permission. If set to true, you will no longer be able to search for a SharePoint site when configuring drive ID, because rclone will not request Sites.Read.All permission. Set it to true if your organization didn't assign Sites.Read.All permission to the application, and your organization disallows users to consent app permission request on their own.",
		command: '--onedrive-disable-site-permission',
	},
	{
		label: 'Expose OneNote Files',
		value: 'expose_onenote_files',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Set to make OneNote files show up in directory listings. By default, rclone will hide OneNote files in directory listings because operations like "Open" and "Update" won\'t work on them.  But this behaviour may also prevent you from deleting them.  If you want to delete OneNote files or otherwise want them to show up in directory listing, set this option.',
		command: '--onedrive-expose-onenote-files',
	},
	{
		label: 'Server Side Across Configs',
		value: 'server_side_across_configs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Deprecated: use --server-side-across-configs instead. Allow server-side operations (e.g. copy) to work across different onedrive configs.',
		command: '--onedrive-server-side-across-configs',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '1000',
		description: 'Size of listing chunk.',
		command: '--onedrive-list-chunk',
	},
	{
		label: 'No Versions',
		value: 'no_versions',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Remove all versions on modifying operations. Onedrive for business creates versions when rclone uploads new files overwriting an existing one and when it sets the modification time.',
		command: '--onedrive-no-versions',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Permanently delete files on removal. Normally files will get sent to the recycle bin on deletion. Setting this flag causes them to be permanently deleted. Use with care.',
		command: '--onedrive-hard-delete',
	},
	{
		label: 'Link Scope',
		value: 'link_scope',
		fieldType: 'string',
		required: false,
		default: 'anonymous',
		description: 'Set the scope of the links created by the link command.',
		command: '--onedrive-link-scope',
	},
	{
		label: 'Link Type',
		value: 'link_type',
		fieldType: 'string',
		required: false,
		default: 'view',
		description: 'Set the type of the links created by the link command.',
		command: '--onedrive-link-type',
	},
	{
		label: 'Link Password',
		value: 'link_password',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Set the password for links created by the link command. At the time of writing this only works with OneDrive personal paid accounts.',
		command: '--onedrive-link-password',
	},
	{
		label: 'Hash Type',
		value: 'hash_type',
		fieldType: 'string',
		required: false,
		default: 'auto',
		description:
			'Specify the hash in use for the backend. This specifies the hash type in use. If set to "auto" it will use the default hash which is QuickXorHash.',
		command: '--onedrive-hash-type',
	},
	{
		label: 'AV Override',
		value: 'av_override',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Allows download of files the server thinks has a virus. The onedrive/sharepoint server may check files uploaded with an Anti Virus checker. If it detects any potential viruses or malware it will block download of the file.',
		command: '--onedrive-av-override',
	},
	{
		label: 'Delta',
		value: 'delta',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If set rclone will use delta listing to implement recursive listings. If this flag is set the onedrive backend will advertise ListR support for recursive listings.',
		command: '--onedrive-delta',
	},
	{
		label: 'Metadata Permissions',
		value: 'metadata_permissions',
		fieldType: 'bits',
		required: false,
		default: 'off',
		description:
			"Control whether permissions should be read or written in metadata. Reading permissions metadata from files can be done quickly, but it isn't always desirable to set the permissions from the metadata.",
		command: '--onedrive-metadata-permissions',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default:
			'slash,ltgt,doublequote,colon,question,asterisk,pipe,backslash,del,ctl,leftspace,lefttilde,rightspace,rightperiod,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--onedrive-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--onedrive-description',
	},
];

export default onedriveSettings;
