const onedriveSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--onedrive-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--onedrive-client-secret',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'select',
		authFieldType: 'client',
		required: false,
		default: 'global',
		options: [
			{ label: 'Microsoft Cloud Global', value: 'global' },
			{ label: 'Microsoft Cloud for US Government', value: 'us' },
			{ label: 'Microsoft Cloud Germany', value: 'de' },
			{ label: 'Azure and Office 365 operated by Vnet Group in China', value: 'cn' },
		],
		description: 'Choose national cloud region for OneDrive.',
		command: '--onedrive-region',
	},
	{
		label: 'Tenant ID',
		value: 'tenant',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			"ID of the service principal's tenant (also called Directory ID).",
		command: '--onedrive-tenant',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--onedrive-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--onedrive-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--onedrive-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Use client credentials OAuth flow instead of interactive login.',
		command: '--onedrive-client-credentials',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description:
			'Size of upload chunks. Must be a multiple of 320 KB and should not exceed 250 MB.',
		command: '--onedrive-chunk-size',
	},
	{
		label: 'Drive ID',
		value: 'drive_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The ID of the drive to use.',
		command: '--onedrive-drive-id',
	},
	{
		label: 'Drive Type',
		value: 'drive_type',
		fieldType: 'select',
		required: false,
		default: '',
		description: 'The type of the drive.',
		command: '--onedrive-drive-type',
		options: [
			{ label: 'Default', value: '' },
			{ label: 'Personal', value: 'personal' },
			{ label: 'Business', value: 'business' },
			{ label: 'Document Library (SharePoint)', value: 'documentLibrary' },
		],
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"ID of the root folder. Only needed if you can't navigate to the desired folder by path.",
		command: '--onedrive-root-folder-id',
	},
	{
		label: 'Access Scopes',
		value: 'access_scopes',
		fieldType: 'spaceseplist',
		required: false,
		default:
			'files.read files.readwrite files.read.all files.readwrite.all sites.read.all offline_access',
		description:
			'Access permissions to request from OneDrive. Choose or enter a custom space-separated list of scopes.',
		command: '--onedrive-access-scopes',
	},
	{
		label: 'Disable Site Permission',
		value: 'disable_site_permission',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Disable the request for Sites.Read.All permission. If enabled, you won't be able to search for SharePoint sites when configuring Drive ID. Use this if your organization doesn't allow this permission.",
		command: '--onedrive-disable-site-permission',
	},
	{
		label: 'Expose OneNote Files',
		value: 'expose_onenote_files',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Show OneNote files in directory listings. OneNote files are hidden by default since they can't be opened or modified, but enabling this allows you to see and delete them.",
		command: '--onedrive-expose-onenote-files',
	},
	{
		label: 'Server Side Across Configs',
		value: 'server_side_across_configs',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Deprecated. Allow server-side operations (e.g., copy) to work across different OneDrive configurations.',
		command: '--onedrive-server-side-across-configs',
	},
	{
		label: 'List Chunk',
		value: 'list_chunk',
		fieldType: 'int',
		required: false,
		default: '1000',
		description: 'Size of listing chunk.',
		command: '--onedrive-list-chunk',
	},
	{
		label: 'No Versions',
		value: 'no_versions',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Remove all previous versions when files are modified. OneDrive for Business creates a new version on each upload.',
		command: '--onedrive-no-versions',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Permanently delete files instead of sending them to the recycle bin. Use with care.',
		command: '--onedrive-hard-delete',
	},
	{
		label: 'Link Scope',
		value: 'link_scope',
		fieldType: 'select',
		required: false,
		default: 'anonymous',
		description: 'Set the visibility scope of shared links.',
		command: '--onedrive-link-scope',
		options: [
			{ label: 'Anyone with the link', value: 'anonymous' },
			{ label: 'Organization (tenant)', value: 'organization' },
		],
	},
	{
		label: 'Link Type',
		value: 'link_type',
		fieldType: 'select',
		required: false,
		default: 'view',
		description: 'Set the permission type of shared links.',
		command: '--onedrive-link-type',
		options: [
			{ label: 'Read-only', value: 'view' },
			{ label: 'Read-write', value: 'edit' },
			{ label: 'Embeddable', value: 'embed' },
		],
	},
	{
		label: 'Link Password',
		value: 'link_password',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Set a password for shared links. Only works with OneDrive Personal paid accounts.',
		command: '--onedrive-link-password',
	},
	{
		label: 'Hash Type',
		value: 'hash_type',
		fieldType: 'select',
		required: false,
		default: 'auto',
		description:
			'Hash algorithm used for file verification. "Auto" uses the recommended QuickXorHash.',
		command: '--onedrive-hash-type',
		options: [
			{ label: 'Auto (recommended)', value: 'auto' },
			{ label: 'QuickXorHash', value: 'quickxor' },
			{ label: 'SHA1', value: 'sha1' },
			{ label: 'SHA256', value: 'sha256' },
			{ label: 'CRC32', value: 'crc32' },
			{ label: 'None', value: 'none' },
		],
	},
	{
		label: 'AV Override',
		value: 'av_override',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Allow downloading files that OneDrive has flagged as potential viruses or malware.',
		command: '--onedrive-av-override',
	},
	{
		label: 'Delta',
		value: 'delta',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Use delta queries for faster recursive folder listings.',
		command: '--onedrive-delta',
	},
	{
		label: 'Metadata Permissions',
		value: 'metadata_permissions',
		fieldType: 'bits',
		required: false,
		default: 'off',
		description:
			'Control whether file permissions should be read or written in metadata.',
		command: '--onedrive-metadata-permissions',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default:
			'slash,ltgt,doublequote,colon,question,asterisk,pipe,backslash,del,ctl,leftspace,lefttilde,rightspace,rightperiod,invalidutf8,dot',
		description: 'Character encoding for file and folder names.',
		command: '--onedrive-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--onedrive-description',
	},
];

export default onedriveSettings;
