const oracleSettings = [
	{
		label: 'Auth Provider',
		value: 'provider',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: 'env_auth',
		description: 'Choose your Auth Provider',
		command: '--oos-provider',
	},
	{
		label: 'Object Storage Namespace',
		value: 'namespace',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Object storage namespace',
		command: '--oos-namespace',
	},
	{
		label: 'Compartment OCID',
		value: 'compartment',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Specify compartment OCID, if you need to list buckets. List objects works without compartment OCID.',
		command: '--oos-compartment',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Object storage Region',
		command: '--oos-region',
	},
	{
		label: 'API Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Endpoint for Object storage API. Leave blank to use the default endpoint for the region.',
		command: '--oos-endpoint',
	},
	{
		label: 'Config File Path',
		value: 'config_file',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '~/.oci/config',
		description: 'Path to OCI config file',
		command: '--oos-config-file',
	},
	{
		label: 'Config Profile',
		value: 'config_profile',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: 'default',
		description: 'Profile name inside the oci config file',
		command: '--oos-config-profile',
	},
	{
		label: 'Storage Tier',
		value: 'storage_tier',
		fieldType: 'string',
		required: false,
		default: 'standard',
		description:
			'The storage class to use when storing new objects in storage. https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/understandingstoragetiers.htm',
		command: '--oos-storage-tier',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '200mi',
		description:
			'Cutoff for switching to chunked upload. Any files larger than this will be uploaded in chunks of chunk_size. The minimum is 0 and the maximum is 5 GiB.',
		command: '--oos-upload-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '5mi',
		description:
			'Chunk size to use for uploading. Files larger than the Upload Cutoff will be uploaded as multipart uploads using this chunk size.',
		command: '--oos-chunk-size',
	},
	{
		label: 'Max Upload Parts',
		value: 'max_upload_parts',
		fieldType: 'int',
		required: false,
		default: '10000',
		description:
			'Maximum number of parts in a multipart upload. This option defines the maximum number of multipart chunks to use when doing a multipart upload.',
		command: '--oos-max-upload-parts',
	},
	{
		label: 'Upload Concurrency',
		value: 'upload_concurrency',
		fieldType: 'int',
		required: false,
		default: '10',
		description:
			'Concurrency for multipart uploads. This is the number of chunks of the same file that are uploaded concurrently.',
		command: '--oos-upload-concurrency',
	},
	{
		label: 'Copy Cutoff',
		value: 'copy_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '4.656gi',
		description:
			'Cutoff for switching to multipart copy. Any files larger than this that need to be server-side copied will be copied in chunks of this size.',
		command: '--oos-copy-cutoff',
	},
	{
		label: 'Copy Timeout',
		value: 'copy_timeout',
		fieldType: 'duration',
		required: false,
		default: '1m0s',
		description:
			'Timeout for copy. Copy is an asynchronous operation, specify timeout to wait for copy to succeed',
		command: '--oos-copy-timeout',
	},
	{
		label: 'Disable Checksum',
		value: 'disable_checksum',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Don't store MD5 checksum with object metadata. This speeds up uploads of large files but reduces data integrity checking.",
		command: '--oos-disable-checksum',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,invalidutf8,dot',
		description: 'The encoding for the backend.',
		command: '--oos-encoding',
	},
	{
		label: 'Leave Parts On Error',
		value: 'leave_parts_on_error',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If true avoid calling abort upload on a failure, leaving all successfully uploaded parts for manual recovery. It should be set to true for resuming uploads across different sessions.',
		command: '--oos-leave-parts-on-error',
	},
	{
		label: 'Attempt Resume Upload',
		value: 'attempt_resume_upload',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If true attempt to resume previously started multipart upload for the object. This will be helpful to speed up multipart transfers by resuming uploads from past session. WARNING: If chunk size differs in resumed session from past incomplete session, then the resumed multipart upload is aborted and a new multipart upload is started with the new chunk size.',
		command: '--oos-attempt-resume-upload',
	},
	{
		label: 'No Check Bucket',
		value: 'no_check_bucket',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"If set, don't attempt to check the bucket exists or create it. Useful if you know the bucket already exists and want to reduce API calls.",
		command: '--oos-no-check-bucket',
	},
	{
		label: 'SSE Customer Key File',
		value: 'sse_customer_key_file',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"To use SSE-C, a file containing the base64-encoded AES-256 encryption key. Only one of SSE Customer Key File, SSE Customer Key, or SSE KMS Key ID is needed.",
		command: '--oos-sse-customer-key-file',
	},
	{
		label: 'SSE Customer Key',
		value: 'sse_customer_key',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'To use SSE-C, the base64-encoded 256-bit encryption key for encrypting or decrypting data. Only one of SSE Customer Key File, SSE Customer Key, or SSE KMS Key ID is needed.',
		command: '--oos-sse-customer-key',
	},
	{
		label: 'SSE Customer Key SHA256',
		value: 'sse_customer_key_sha256',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'If using SSE-C, the base64-encoded SHA256 hash of the encryption key. Used to verify the integrity of the encryption key.',
		command: '--oos-sse-customer-key-sha256',
	},
	{
		label: 'SSE KMS Key ID',
		value: 'sse_kms_key_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'If using your own master key in vault, the OCID of the master encryption key for the Key Management service. Only one of SSE Customer Key File, SSE Customer Key, or SSE KMS Key ID is needed.',
		command: '--oos-sse-kms-key-id',
	},
	{
		label: 'SSE Customer Algorithm',
		value: 'sse_customer_algorithm',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'If using SSE-C, the encryption algorithm. Object Storage supports "AES256".',
		command: '--oos-sse-customer-algorithm',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--oos-description',
	},
];

export default oracleSettings;
