const oracleSettings = [
	{
		label: 'Auth Provider',
		value: 'provider',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: 'env_auth',
		description: 'Choose your Auth Provider',
		command: '--oos-provider',
	},
	{
		label: 'Object Storage Namespace',
		value: 'namespace',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Object storage namespace',
		command: '--oos-namespace',
	},
	{
		label: 'Compartment OCID',
		value: 'compartment',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Specify compartment OCID, if you need to list buckets. List objects works without compartment OCID.',
		command: '--oos-compartment',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Object storage Region',
		command: '--oos-region',
	},
	{
		label: 'API Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description:
			'Endpoint for Object storage API. Leave blank to use the default endpoint for the region.',
		command: '--oos-endpoint',
	},
	{
		label: 'Config File Path',
		value: 'config_file',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '~/.oci/config',
		description: 'Path to OCI config file',
		command: '--oos-config-file',
	},
	{
		label: 'Config Profile',
		value: 'config_profile',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: 'default',
		description: 'Profile name inside the oci config file',
		command: '--oos-config-profile',
	},
	{
		label: 'Storage Tier',
		value: 'storage_tier',
		fieldType: 'string',
		required: false,
		default: 'standard',
		description:
			'The storage class to use when storing new objects in storage. https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/understandingstoragetiers.htm',
		command: '--oos-storage-tier',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '200mi',
		description:
			'Cutoff for switching to chunked upload. Any files larger than this will be uploaded in chunks of chunk_size. The minimum is 0 and the maximum is 5 GiB.',
		command: '--oos-upload-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '5mi',
		description:
			'Chunk size to use for uploading. When uploading files larger than upload_cutoff or files with unknown size (e.g. from "rclone rcat" or uploaded with "rclone mount" they will be uploaded as multipart uploads using this chunk size.',
		command: '--oos-chunk-size',
	},
	{
		label: 'Max Upload Parts',
		value: 'max_upload_parts',
		fieldType: 'int',
		required: false,
		default: '10000',
		description:
			'Maximum number of parts in a multipart upload. This option defines the maximum number of multipart chunks to use when doing a multipart upload.',
		command: '--oos-max-upload-parts',
	},
	{
		label: 'Upload Concurrency',
		value: 'upload_concurrency',
		fieldType: 'int',
		required: false,
		default: '10',
		description:
			'Concurrency for multipart uploads. This is the number of chunks of the same file that are uploaded concurrently.',
		command: '--oos-upload-concurrency',
	},
	{
		label: 'Copy Cutoff',
		value: 'copy_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '4.656gi',
		description:
			'Cutoff for switching to multipart copy. Any files larger than this that need to be server-side copied will be copied in chunks of this size.',
		command: '--oos-copy-cutoff',
	},
	{
		label: 'Copy Timeout',
		value: 'copy_timeout',
		fieldType: 'duration',
		required: false,
		default: '1m0s',
		description:
			'Timeout for copy. Copy is an asynchronous operation, specify timeout to wait for copy to succeed',
		command: '--oos-copy-timeout',
	},
	{
		label: 'Disable Checksum',
		value: 'disable_checksum',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Don't store MD5 checksum with object metadata. Normally rclone will calculate the MD5 checksum of the input before uploading it so it can add it to metadata on the object. This is great for data integrity checking but can cause long delays for large files to start uploading.",
		command: '--oos-disable-checksum',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--oos-encoding',
	},
	{
		label: 'Leave Parts On Error',
		value: 'leave_parts_on_error',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If true avoid calling abort upload on a failure, leaving all successfully uploaded parts for manual recovery. It should be set to true for resuming uploads across different sessions.',
		command: '--oos-leave-parts-on-error',
	},
	{
		label: 'Attempt Resume Upload',
		value: 'attempt_resume_upload',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If true attempt to resume previously started multipart upload for the object. This will be helpful to speed up multipart transfers by resuming uploads from past session. WARNING: If chunk size differs in resumed session from past incomplete session, then the resumed multipart upload is aborted and a new multipart upload is started with the new chunk size.',
		command: '--oos-attempt-resume-upload',
	},
	{
		label: 'No Check Bucket',
		value: 'no_check_bucket',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"If set, don't attempt to check the bucket exists or create it. This can be useful when trying to minimise the number of transactions rclone does if you know the bucket exists already.",
		command: '--oos-no-check-bucket',
	},
	{
		label: 'SSE Customer Key File',
		value: 'sse_customer_key_file',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"To use SSE-C, a file containing the base64-encoded string of the AES-256 encryption key associated with the object. Please note only one of sse_customer_key_file|sse_customer_key|sse_kms_key_id is needed.'",
		command: '--oos-sse-customer-key-file',
	},
	{
		label: 'SSE Customer Key',
		value: 'sse_customer_key',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'To use SSE-C, the optional header that specifies the base64-encoded 256-bit encryption key to use to encrypt or  decrypt the data. Please note only one of sse_customer_key_file|sse_customer_key|sse_kms_key_id is needed. For more information, see Using Your Own Keys for Server-Side Encryption (https://docs.cloud.oracle.com/Content/Object/Tasks/usingyourencryptionkeys.htm)',
		command: '--oos-sse-customer-key',
	},
	{
		label: 'SSE Customer Key SHA256',
		value: 'sse_customer_key_sha256',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'If using SSE-C, The optional header that specifies the base64-encoded SHA256 hash of the encryption key. This value is used to check the integrity of the encryption key. see Using Your Own Keys for Server-Side Encryption (https://docs.cloud.oracle.com/Content/Object/Tasks/usingyourencryptionkeys.htm).',
		command: '--oos-sse-customer-key-sha256',
	},
	{
		label: 'SSE KMS Key ID',
		value: 'sse_kms_key_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'if using your own master key in vault, this header specifies the OCID (https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of a master encryption key used to call the Key Management service to generate a data encryption key or to encrypt or decrypt a data encryption key. Please note only one of sse_customer_key_file|sse_customer_key|sse_kms_key_id is needed.',
		command: '--oos-sse-kms-key-id',
	},
	{
		label: 'SSE Customer Algorithm',
		value: 'sse_customer_algorithm',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'If using SSE-C, the optional header that specifies "AES256" as the encryption algorithm. Object Storage supports "AES256" as the encryption algorithm. For more information, see Using Your Own Keys for Server-Side Encryption (https://docs.cloud.oracle.com/Content/Object/Tasks/usingyourencryptionkeys.htm).',
		command: '--oos-sse-customer-algorithm',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--oos-description',
	},
];

export default oracleSettings;
