import s3Options from './_s3Options';

const ossSettings = [
	{
		label: 'Access Key ID',
		value: 'access_key_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Alibaba Cloud Access Key ID.',
		command: '--s3-access-key-id',
	},
	{
		label: 'Secret Access Key',
		value: 'secret_access_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Alibaba Cloud Secret Access Key (password).',
		command: '--s3-secret-access-key',
	},
	{
		label: 'Region',
		value: 'endpoint',
		fieldType: 'select',
		authFieldType: 'client',
		allowCustom: true,
		options: [
			{ label: 'Select Region', value: '' },
			{ label: 'China (Hangzhou)', value: 'oss-cn-hangzhou.aliyuncs.com' },
			{ label: 'China (Shanghai)', value: 'oss-cn-shanghai.aliyuncs.com' },
			{ label: 'China (Nanjing-Local Region)', value: 'oss-cn-nanjing.aliyuncs.com' },
			{ label: 'China (Qingdao)', value: 'oss-cn-qingdao.aliyuncs.com' },
			{ label: 'China (Beijing)', value: 'oss-cn-beijing.aliyuncs.com' },
			{ label: 'China (Zhangjiakou)', value: 'oss-cn-zhangjiakou.aliyuncs.com' },
			{ label: 'China (Hohhot)', value: 'oss-cn-huhehaote.aliyuncs.com' },
			{ label: 'China (Ulanqab)', value: 'oss-cn-wulanchabu.aliyuncs.com' },
			{ label: 'China (Shenzhen)', value: 'oss-cn-shenzhen.aliyuncs.com' },
			{ label: 'China (Heyuan)', value: 'oss-cn-heyuan.aliyuncs.com' },
			{ label: 'China (Guangzhou)', value: 'oss-cn-guangzhou.aliyuncs.com' },
			{ label: 'China (Chengdu)', value: 'oss-cn-chengdu.aliyuncs.com' },
			{ label: 'China (Hong Kong)', value: 'oss-cn-hongkong.aliyuncs.com' },
			{ label: 'Japan (Tokyo)', value: 'oss-ap-northeast-1.aliyuncs.com' },
			{ label: 'South Korea (Seoul)', value: 'oss-ap-northeast-2.aliyuncs.com' },
			{ label: 'Singapore', value: 'oss-ap-southeast-1.aliyuncs.com' },
			{ label: 'Malaysia (Kuala Lumpur)', value: 'oss-ap-southeast-3.aliyuncs.com' },
			{ label: 'Indonesia (Jakarta)', value: 'oss-ap-southeast-5.aliyuncs.com' },
			{ label: 'Philippines (Manila)', value: 'oss-ap-southeast-6.aliyuncs.com' },
			{ label: 'Thailand (Bangkok)', value: 'oss-ap-southeast-7.aliyuncs.com' },
			{ label: 'Germany (Frankfurt)', value: 'oss-eu-central-1.aliyuncs.com' },
			{ label: 'UK (London)', value: 'oss-eu-west-1.aliyuncs.com' },
			{ label: 'US (Silicon Valley)', value: 'oss-us-west-1.aliyuncs.com' },
			{ label: 'US (Virginia)', value: 'oss-us-east-1.aliyuncs.com' },
			{ label: 'UAE (Dubai)', value: 'oss-me-east-1.aliyuncs.com' },
			{ label: 'SAU (Riyadh - Partner Region)', value: 'oss-me-central-1.aliyuncs.com' },
			{ label: 'Insert Custon Endpoint', value: 'custom' },
		],
		required: true,
		default: '',
		description:
			"Select a Region to connect to that region's API Endpoint.",
		command: '--s3-region',
	},
	{
		label: 'Access Control List (ACL)',
		value: 'acl',
		fieldType: 'select',
		authFieldType: 'client',
		options: [
			{ label: 'Default', value: '' },
			{ label: 'private (Only the object owner can read/write)', value: 'private' },
			{
				label: 'Public Read (object owner can read/write, others read-only)',
				value: 'public-read',
			},
			{ label: 'Public Read/Write (All Usergroup can read/write)', value: 'public-read-write' },
		],
		required: false,
		default: '',
		description:
			'Access control permissions applied when creating buckets and storing objects.',
		command: '--s3-acl',
	},
	{
		label: 'Storage Class',
		value: 'storage_class',
		fieldType: 'select',
		authFieldType: 'client',
		options: [
			{ label: 'Default', value: '' },
			{ label: 'private (Only the object owner can read/write)', value: 'private' },
			{
				label: 'Public Read (Object owner can read/write, others read-only)',
				value: 'public-read',
			},
			{ label: 'Public Read/Write (All Usergroup can read/write)', value: 'public-read-write' },
		],
		required: false,
		default: '',
		description: 'The storage class to use when storing new objects in OSS.',
		command: '--s3-storage_class',
	},
	...s3Options,
];

export default ossSettings;
