const pcloudSettings = [
	{
		label: 'Client Id',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--pcloud-client-id',
	},
	{
		label: 'OAuth Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Client Secret. Leave blank normally.',
		command: '--pcloud-client-secret',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--pcloud-token',
	},
	{
		label: 'Auth Server URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--pcloud-auth-url',
	},
	{
		label: 'Token Server URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--pcloud-token-url',
	},
	{
		label: 'Use client credentials OAuth',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--pcloud-client-credentials',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend.',
		command: '--pcloud-encoding',
	},
	{
		label: 'Non-root folder Id',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: 'd0',
		description: 'Set a non-root folder as the starting point.',
		command: '--pcloud-root-folder-id',
	},
	{
		label: 'Hostname',
		value: 'hostname',
		fieldType: 'select',
		required: false,
		default: 'api.pcloud.com',
		description:
			'Hostname to connect to. This is normally set automatically during the OAuth connection. Change only if you need to use a different region.',
		command: '--pcloud-hostname',
		options: [
			{ label: 'US / Global', value: 'api.pcloud.com' },
			{ label: 'EU', value: 'eapi.pcloud.com' },
		],
	},
	{
		label: 'Username',
		value: 'username',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description:
			'Your pcloud username. Only required if you want to use the cleanup command.',
		command: '--pcloud-username',
	},
	{
		label: 'Password',
		value: 'password',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: 'Your pcloud password.',
		command: '--pcloud-password',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--pcloud-description',
	},
];

export default pcloudSettings;
