const pcloudSettings = [
	{
		label: 'Client Id',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--pcloud-client-id',
	},
	{
		label: 'OAuth Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Client Secret. Leave blank normally.',
		command: '--pcloud-client-secret',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--pcloud-token',
	},
	{
		label: 'Auth Server URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--pcloud-auth-url',
	},
	{
		label: 'Token Server URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--pcloud-token-url',
	},
	{
		label: 'Use client credentials OAuth',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--pcloud-client-credentials',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--pcloud-encoding',
	},
	{
		label: 'Non-root folder Id',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: 'd0',
		description: 'Fill in for rclone to use a non root folder as its starting point.',
		command: '--pcloud-root-folder-id',
	},
	{
		label: 'Hostname',
		value: 'hostname',
		fieldType: 'string',
		required: false,
		default: 'api.pcloud.com',
		description:
			'Hostname to connect to. This is normally set when rclone initially does the oauth connection,\nhowever you will need to set it by hand if you are using storage config\nwith rclone authorize.',
		command: '--pcloud-hostname',
	},
	{
		label: 'Username',
		value: 'username',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description:
			'Your pcloud username. This is only required when you want to use the cleanup command. Due to a bug\nin the pcloud API the required API does not support OAuth authentication so\nwe have to rely on user password authentication for it.',
		command: '--pcloud-username',
	},
	{
		label: 'Password',
		value: 'password',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: 'Your pcloud password. NB Input to this must be obscured - see rclone obscure.',
		command: '--pcloud-password',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--pcloud-description',
	},
];

export default pcloudSettings;
