const protondriveSettings = [
	{
		label: 'Username',
		value: 'username',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'The username of your proton account',
		command: '--protondrive-username',
	},
	{
		label: 'Password',
		value: 'password',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'The password of your Proton account.',
		command: '--protondrive-password',
	},
	{
		label: '2FA Code',
		value: '2fa',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The 2FA code for your Proton account, if 2FA is enabled.',
		command: '--protondrive-2fa',
	},
	{
		label: 'Mailbox Password',
		value: 'mailbox_password',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'The mailbox password of your two-password proton account. For more information regarding the mailbox password, please check the following official knowledge base article: https://proton.me/support/the-difference-between-the-mailbox-password-and-login-password',
		command: '--protondrive-mailbox-password',
	},
	{
		label: 'Client UID',
		value: 'client_uid',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Client uid key (internal use only)',
		command: '--protondrive-client-uid',
	},
	{
		label: 'Client Access Token',
		value: 'client_access_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Client access token key (internal use only)',
		command: '--protondrive-client-access-token',
	},
	{
		label: 'Client Refresh Token',
		value: 'client_refresh_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Client refresh token key (internal use only)',
		command: '--protondrive-client-refresh-token',
	},
	{
		label: 'Client Salted Key Pass',
		value: 'client_salted_key_pass',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Client salted key pass key (internal use only)',
		command: '--protondrive-client-salted-key-pass',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,leftspace,rightspace,invalidutf8,dot',
		description: 'The encoding for the backend.',
		command: '--protondrive-encoding',
	},
	{
		label: 'Original File Size',
		value: 'original_file_size',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Return the file size before encryption. The encrypted file size will be larger than the original.',
		command: '--protondrive-original-file-size',
	},
	{
		label: 'App Version',
		value: 'app_version',
		fieldType: 'string',
		required: false,
		default: 'macos-drive@1.0.0-alpha.1+rclone"',
		description:
			'The app version string sent with every API request.',
		command: '--protondrive-app-version',
	},
	{
		label: 'Replace Existing Draft',
		value: 'replace_existing_draft',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Create a new revision when a filename conflict is detected due to a previously cancelled or failed upload.',
		command: '--protondrive-replace-existing-draft',
	},
	{
		label: 'Enable Caching',
		value: 'enable_caching',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Caches files and folders metadata to reduce API calls. Disable if external changes need to be reflected immediately.',
		command: '--protondrive-enable-caching',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--protondrive-description',
	},
];

export default protondriveSettings;
