const putioSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--putio-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--putio-client-secret',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--putio-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--putio-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--putio-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--putio-client-credentials',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--putio-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--putio-description',
	},
];

export default putioSettings;
