const quatrixSettings = [
	{
		label: 'API Key',
		value: 'api_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'API key for accessing Quatrix account',
		command: '--quatrix-api-key',
	},
	{
		label: 'Host Name',
		value: 'host',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Host name of Quatrix account. example: example.quatrix.it',
		command: '--quatrix-host',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,backslash,del,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--quatrix-encoding',
	},
	{
		label: 'Upload Time',
		value: 'effective_upload_time',
		fieldType: 'string',
		required: false,
		default: '4s',
		description: 'Wanted upload time for one chunk',
		command: '--quatrix-effective-upload-time',
	},
	{
		label: 'Minimal Chunk Size',
		value: 'minimal_chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '9.537mi',
		description: 'The minimal size for one chunk',
		command: '--quatrix-minimal-chunk-size',
	},
	{
		label: 'Max Summary Chunk Size',
		value: 'maximal_summary_chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '95.367mi',
		description:
			"The maximal summary for all chunks. It should not be less than 'transfers'*'minimal_chunk_size'",
		command: '--quatrix-maximal-summary-chunk-size',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Delete files permanently rather than putting them into the trash',
		command: '--quatrix-hard-delete',
	},
	{
		label: 'Skip Project Folders',
		value: 'skip_project_folders',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Skip project folders in operations',
		command: '--quatrix-skip-project-folders',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--quatrix-description',
	},
];

export default quatrixSettings;
