const seafileSettings = [
	{
		label: 'Server URL',
		value: 'url',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: 'https://cloud.seafile.com/',
		description: 'URL of seafile host to connect to.',
		command: '--seafile-url',
	},
	{
		label: 'Username',
		value: 'user',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'User name (usually email address).',
		command: '--seafile-user',
	},
	{
		label: 'Password',
		value: 'pass',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: 'Password. NB Input to this must be obscured - see rclone obscure.',
		command: '--seafile-pass',
	},
	{
		label: 'Two-Factor Auth',
		value: '2fa',
		fieldType: 'bool',
		authFieldType: 'password',
		required: true,
		default: false,
		description: "Two-factor authentication ('true' if the account has 2FA enabled).",
		command: '--seafile-2fa',
	},
	{
		label: 'Library Name',
		value: 'library',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Name of the library. Leave blank to access all non-encrypted libraries.',
		command: '--seafile-library',
	},
	{
		label: 'Library Password',
		value: 'library_key',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Library password (for encrypted libraries only). Leave blank if you pass it through the command line.',
		command: '--seafile-library-key',
	},
	{
		label: 'Auth Token',
		value: 'auth_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Authentication token.',
		command: '--seafile-auth-token',
	},
	{
		label: 'Create Library',
		value: 'create_library',
		fieldType: 'bool',
		required: false,
		default: false,
		description: "Should rclone create a library if it doesn't exist.",
		command: '--seafile-create-library',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,doublequote,backslash,ctl,invalidutf8',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--seafile-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--seafile-description',
	},
];

export default seafileSettings;
