const sftpSettings = [
	{
		label: 'SSH Host',
		command: '--sftp-host',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		value: 'host',
		default: '',
		description: 'SSH host to connect to. E.g. "example.com".',
	},
	{
		label: 'SSH Username',
		command: '--sftp-user',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		value: 'user',
		default: '$user',
		description: 'SSH username.',
	},
	{
		label: 'SSH Port',
		command: '--sftp-port',
		fieldType: 'int',
		authFieldType: 'password',
		required: false,
		value: 'port',
		default: '22',
		description: 'SSH port number.',
	},
	{
		label: 'SSH Password',
		command: '--sftp-pass',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		value: 'pass',
		default: '',
		description:
			'SSH password, leave blank to use ssh-agent. NB Input to this must be obscured - see rclone obscure.',
	},
	{
		label: 'PEM-Encoded Private Key',
		command: '--sftp-key-pem',
		fieldType: 'string',
		required: false,
		value: 'key_pem',
		default: '',
		description:
			"Raw PEM-encoded private key. Note that this should be on a single line with line endings replaced with '\\n', eg",
	},
	{
		label: 'Private Key File',
		command: '--sftp-key-file',
		fieldType: 'string',
		required: false,
		value: 'key_file',
		default: '',
		description:
			'Path to PEM-encoded private key file. Leave blank or set key-use-agent to use ssh-agent.',
	},
	{
		label: 'Private Key Passphrase',
		command: '--sftp-key-file-pass',
		fieldType: 'string',
		required: false,
		value: 'key_file_pass',
		default: '',
		description:
			"The passphrase to decrypt the PEM-encoded private key file. Only PEM encrypted key files (old OpenSSH format) are supported. Encrypted keys\nin the new OpenSSH format can't be used.",
	},
	{
		label: 'SSH Public Certificate',
		command: '--sftp-pubkey',
		fieldType: 'string',
		required: false,
		value: 'pubkey',
		default: '',
		description:
			'SSH public certificate for public certificate based authentication.\nSet this if you have a signed certificate you want to use for authentication.\nIf specified will override pubkey_file.',
	},
	{
		label: 'Public Key File',
		command: '--sftp-pubkey-file',
		fieldType: 'string',
		required: false,
		value: 'pubkey_file',
		default: '',
		description:
			'Optional path to public key file. Set this if you have a signed certificate you want to use for authentication.',
	},
	{
		label: 'Use SSH Agent',
		command: '--sftp-key-use-agent',
		fieldType: 'bool',
		required: false,
		value: 'key_use_agent',
		default: false,
		description:
			'When set forces the usage of the ssh-agent. When key-file is also set, the ".pub" file of the specified key-file is read and only the associated key is\nrequested from the ssh-agent. This allows to avoid Too many authentication failures for *username* errors\nwhen the ssh-agent contains many keys.',
	},
	{
		label: 'Allow Insecure Ciphers',
		command: '--sftp-use-insecure-cipher',
		fieldType: 'bool',
		required: false,
		value: 'use_insecure_cipher',
		default: false,
		description:
			'Enable the use of insecure ciphers and key exchange methods. This enables the use of the following insecure ciphers and key exchange methods:',
	},
	{
		label: 'Disable Hash Check',
		command: '--sftp-disable-hashcheck',
		fieldType: 'bool',
		required: false,
		value: 'disable_hashcheck',
		default: false,
		description:
			'Disable the execution of SSH commands to determine if remote file hashing is available. Leave blank or set to false to enable hashing (recommended), set to true to disable hashing.',
	},
	{
		label: 'External SSH Binary',
		command: '--sftp-ssh',
		fieldType: 'spaceseplist',
		required: false,
		value: 'ssh',
		default: '',
		description:
			'Path and arguments to external ssh binary. Normally rclone will use its internal ssh library to connect to the\nSFTP server. However it does not implement all possible ssh options so\nit may be desirable to use an external ssh binary.',
	},
	{
		label: 'Known Hosts File',
		command: '--sftp-known-hosts-file',
		fieldType: 'string',
		required: false,
		value: 'known_hosts_file',
		default: '',
		description:
			'Optional path to known_hosts file. Set this value to enable server host key validation.',
	},
	{
		label: 'Ask for Password',
		command: '--sftp-ask-password',
		fieldType: 'bool',
		required: false,
		value: 'ask_password',
		default: false,
		description:
			'Allow asking for SFTP password when needed. If this is set and no password is supplied then rclone will:',
	},
	{
		label: 'SSH Path Override',
		command: '--sftp-path-override',
		fieldType: 'string',
		required: false,
		value: 'path_override',
		default: '',
		description:
			'Override path used by SSH shell commands. This allows checksum calculation when SFTP and SSH paths are\ndifferent. This issue affects among others Synology NAS boxes.',
	},
	{
		label: 'Set Remote Modified Time',
		command: '--sftp-set-modtime',
		fieldType: 'bool',
		required: false,
		value: 'set_modtime',
		default: true,
		description: 'Set the modified time on the remote if set.',
	},
	{
		label: 'Remote Shell Type',
		command: '--sftp-shell-type',
		fieldType: 'string',
		required: false,
		value: 'shell_type',
		default: '',
		description: 'The type of SSH shell on remote server, if any. Leave blank for autodetect.',
	},
	{
		label: 'MD5 Hash Command',
		command: '--sftp-md5sum-command',
		fieldType: 'string',
		required: false,
		value: 'md5sum_command',
		default: '',
		description: 'The command used to read md5 hashes. Leave blank for autodetect.',
	},
	{
		label: 'SHA1 Hash Command',
		command: '--sftp-sha1sum-command',
		fieldType: 'string',
		required: false,
		value: 'sha1sum_command',
		default: '',
		description: 'The command used to read sha1 hashes. Leave blank for autodetect.',
	},
	{
		label: 'Skip Symlinks',
		command: '--sftp-skip-links',
		fieldType: 'bool',
		required: false,
		value: 'skip_links',
		default: false,
		description: 'Set to skip any symlinks and any other non regular files.',
	},
	{
		label: 'SSH Subsystem',
		command: '--sftp-subsystem',
		fieldType: 'string',
		required: false,
		value: 'subsystem',
		default: 'sftp',
		description: 'Specifies the SSH2 subsystem on the remote host.',
	},
	{
		label: 'SFTP Server Command',
		command: '--sftp-server-command',
		fieldType: 'string',
		required: false,
		value: 'server_command',
		default: '',
		description:
			'Specifies the path or command to run a sftp server on the remote host. The subsystem option is ignored when server_command is defined.',
	},
	{
		label: 'Use fstat Instead of stat',
		command: '--sftp-use-fstat',
		fieldType: 'bool',
		required: false,
		value: 'use_fstat',
		default: false,
		description:
			'If set use fstat instead of stat. Some servers limit the amount of open files and calling Stat after opening\nthe file will throw an error from the server. Setting this flag will call\nFstat instead of Stat which is called on an already open file handle.',
	},
	{
		label: 'Disable Concurrent Reads',
		command: '--sftp-disable-concurrent-reads',
		fieldType: 'bool',
		required: false,
		value: 'disable_concurrent_reads',
		default: false,
		description:
			"If set don't use concurrent reads. Normally concurrent reads are safe to use and not using them will\ndegrade performance, so this option is disabled by default.",
	},
	{
		label: 'Disable Concurrent Writes',
		command: '--sftp-disable-concurrent-writes',
		fieldType: 'bool',
		required: false,
		value: 'disable_concurrent_writes',
		default: false,
		description:
			"If set don't use concurrent writes. Normally rclone uses concurrent writes to upload files. This improves\nthe performance greatly, especially for distant servers.",
	},
	{
		label: 'Idle Connection Timeout',
		command: '--sftp-idle-timeout',
		fieldType: 'duration',
		required: false,
		value: 'idle_timeout',
		default: '1m0s',
		description:
			'Max time before closing idle connections. If no connections have been returned to the connection pool in the time\ngiven, rclone will empty the connection pool.',
	},
	{
		label: 'Chunk Size',
		command: '--sftp-chunk-size',
		fieldType: 'sizesuffix',
		required: false,
		value: 'chunk_size',
		default: '32ki',
		description:
			'Upload and download chunk size. This controls the maximum size of payload in SFTP protocol packets.\nThe RFC limits this to 32768 bytes (32k), which is the default. However,\na lot of servers support larger sizes, typically limited to a maximum\ntotal package size of 256k, and setting it larger will increase transfer\nspeed dramatically on high latency links. This includes OpenSSH, and,\nfor example, using the value of 255k works well, leaving plenty of room\nfor overhead while still being within a total packet size of 256k.',
	},
	{
		label: 'Max Concurrent Requests per File',
		command: '--sftp-concurrency',
		fieldType: 'int',
		required: false,
		value: 'concurrency',
		default: '64',
		description:
			'The maximum number of outstanding requests for one file This controls the maximum number of outstanding requests for one file.\nIncreasing it will increase throughput on high latency links at the\ncost of using more memory.',
	},
	{
		label: 'Max Simultaneous Connections',
		command: '--sftp-connections',
		fieldType: 'int',
		required: false,
		value: 'connections',
		default: '0',
		description:
			'Maximum number of SFTP simultaneous connections, 0 for unlimited. Note that setting this is very likely to cause deadlocks so it should\nbe used with care.',
	},
	{
		label: 'Environment Variables',
		command: '--sftp-set-env',
		fieldType: 'spaceseplist',
		required: false,
		value: 'set_env',
		default: '',
		description:
			'Environment variables to pass to sftp and commands Set environment variables in the form:',
	},
	{
		label: 'Session Encryption Ciphers',
		command: '--sftp-ciphers',
		fieldType: 'spaceseplist',
		required: false,
		value: 'ciphers',
		default: '',
		description:
			'Space separated list of ciphers to be used for session encryption, ordered by preference. At least one must match with server configuration. This can be checked for example using ssh -Q cipher.',
	},
	{
		label: 'Key Exchange Algorithms',
		command: '--sftp-key-exchange',
		fieldType: 'spaceseplist',
		required: false,
		value: 'key_exchange',
		default: '',
		description:
			'Space separated list of key exchange algorithms, ordered by preference. At least one must match with server configuration. This can be checked for example using ssh -Q kex.',
	},
	{
		label: 'Message Authentication Code (MAC) Algorithms',
		command: '--sftp-macs',
		fieldType: 'spaceseplist',
		required: false,
		value: 'macs',
		default: '',
		description:
			'Space separated list of MACs (message authentication code) algorithms, ordered by preference. At least one must match with server configuration. This can be checked for example using ssh -Q mac.',
	},
	{
		label: 'Host Key Algorithms',
		command: '--sftp-host-key-algorithms',
		fieldType: 'spaceseplist',
		required: false,
		value: 'host_key_algorithms',
		default: '',
		description:
			'Space separated list of host key algorithms, ordered by preference. At least one must match with server configuration. This can be checked for example using ssh -Q HostKeyAlgorithms.',
	},
	{
		label: 'SOCKS Proxy',
		command: '--sftp-socks-proxy',
		fieldType: 'string',
		required: false,
		value: 'socks_proxy',
		default: '',
		description:
			'Socks 5 proxy host. Supports the format user:pass@host:port, user@host:port, host:port.',
	},
	{
		label: 'Enable Hardlink Copy',
		command: '--sftp-copy-is-hardlink',
		fieldType: 'bool',
		required: false,
		value: 'copy_is_hardlink',
		default: false,
		description:
			'Set to enable server side copies using hardlinks. The SFTP protocol does not define a copy command so normally server\nside copies are not allowed with the sftp backend.',
	},
	{
		label: 'Description',
		command: '--sftp-description',
		fieldType: 'string',
		required: false,
		value: 'description',
		default: '',
		description: 'Description of the Storage.',
	},
];

export default sftpSettings;
