const citrixSharefileSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--sharefile-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--sharefile-client-secret',
	},
	{
		label: 'Root Folder ID',
		value: 'root_folder_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'ID of the root folder. Leave blank to access "Personal Folders".  You can use one of the standard values here or any folder ID (long hex number ID).',
		command: '--sharefile-root-folder-id',
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: false,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--sharefile-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--sharefile-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--sharefile-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--sharefile-client-credentials',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '128mi',
		description: 'Cutoff for switching to multipart upload.',
		command: '--sharefile-upload-cutoff',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '64mi',
		description: 'Upload chunk size. Must a power of 2 >= 256k.',
		command: '--sharefile-chunk-size',
	},
	{
		label: 'API Endpoint',
		value: 'endpoint',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Endpoint for API calls. This is usually auto discovered as part of the oauth process, but can be set manually to something like: https://XXX.sharefile.com',
		command: '--sharefile-endpoint',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default:
			'slash,ltgt,doublequote,colon,question,asterisk,pipe,backslash,ctl,leftspace,leftperiod,rightspace,rightperiod,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--sharefile-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--sharefile-description',
	},
];

export default citrixSharefileSettings;
