const smbSettings = [
	{
		label: 'Host',
		value: 'host',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: "SMB server hostname to connect to. E.g., 'example.com'.",
		command: '--smb-host',
	},
	{
		label: 'Username',
		value: 'user',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '$USER',
		description: 'SMB username.',
		command: '--smb-user',
	},
	{
		label: 'Port',
		value: 'port',
		fieldType: 'int',
		authFieldType: 'password',
		required: false,
		default: '445',
		description: 'SMB port number.',
		command: '--smb-port',
	},
	{
		label: 'Password',
		value: 'pass',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: '',
		description: 'SMB password.',
		command: '--smb-pass',
	},
	{
		label: 'Domain',
		value: 'domain',
		fieldType: 'string',
		authFieldType: 'password',
		required: false,
		default: 'WORKGROUP',
		description: 'Domain name for NTLM authentication.',
		command: '--smb-domain',
	},
	{
		label: 'Service Principal Name',
		value: 'spn',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"Service principal name presented to the server. Some servers use this for additional authentication, often needed for clusters. For example: 'cifs/remotehost:1020'. Leave blank if not sure.",
		command: '--smb-spn',
	},
	{
		label: 'Idle Timeout',
		value: 'idle_timeout',
		fieldType: 'duration',
		required: false,
		default: '1m0s',
		description:
			'Max time before closing idle connections. If no connections are used within this time, the connection pool is emptied. Set to 0 to keep connections indefinitely.',
		command: '--smb-idle-timeout',
	},
	{
		label: 'Hide Special Shares',
		value: 'hide_special_share',
		fieldType: 'bool',
		required: false,
		default: true,
		description: "Hide special shares (e.g., print$) which users aren't supposed to access.",
		command: '--smb-hide-special-share',
	},
	{
		label: 'Case Insensitive',
		value: 'case_insensitive',
		fieldType: 'bool',
		required: false,
		default: true,
		description:
			'Whether the server is configured to be case-insensitive. Always true on Windows shares.',
		command: '--smb-case-insensitive',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default:
			'Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,BackSlash,Ctl,RightSpace,RightPeriod,InvalidUtf8,Dot',
		description: 'The encoding for the backend.',
		command: '--smb-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--smb-description',
	},
];

export default smbSettings;
