const storjSettings = [
	{
		label: 'Access Grant',
		value: 'access_grant',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'Access grant.',
		command: '--storj-access-grant',
	},
	{
		label: 'Satellite Address',
		value: 'satellite_address',
		fieldType: 'select',
		authFieldType: 'client',
		required: true,
		default: 'us1.storj.io',
		options: [
			{ label: 'US1', value: 'us1.storj.io' },
			{ label: 'EU1', value: 'eu1.storj.io' },
			{ label: 'AP1', value: 'ap1.storj.io' },
			{ label: 'Custom', value: 'custom' },
		],
		description: 'Custom satellite address should match the format: <nodeid>@<address>:<port>.',
		command: '--storj-satellite-address',
	},
	{
		label: 'API Key',
		value: 'api_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'API key.',
		command: '--storj-api-key',
	},
	{
		label: 'Encryption Passphrase',
		value: 'passphrase',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			'Encryption passphrase. To access existing objects enter passphrase used for uploading.',
		command: '--storj-passphrase',
	},
	{
		label: 'Auth Provider',
		value: 'provider',
		fieldType: 'select',
		authFieldType: 'client',
		required: false,
		default: 'existing',
		description: 'Choose an authentication method.',
		command: '--storj-provider',
		options: [
			{ label: 'Use an existing access grant', value: 'existing' },
			{ label: 'Create a new access grant', value: 'new' },
		],
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--storj-description',
	},
];

export default storjSettings;
