const sugarsyncSettings = [
	{
		label: 'Username (Email Address)',
		value: 'user',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Sugarsync username.',
		command: '--sugarsync-user',
	},
	{
		label: 'Passowrd',
		fieldType: 'string',
		value: 'password',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Your Sugarsync password is only required during setup and will not be stored.',
		command: '',
	},
	{
		label: 'App ID',
		value: 'app_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: "Sugarsync App ID. Leave blank to use rclone's.",
		command: '--sugarsync-app-id',
	},
	{
		label: 'Access Key ID',
		value: 'access_key_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: "Sugarsync Access Key ID. Leave blank to use rclone's.",
		command: '--sugarsync-access-key-id',
	},
	{
		label: 'Private Access Key',
		value: 'private_access_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: false,
		default: '',
		description: "Sugarsync Private Access Key. Leave blank to use rclone's.",
		command: '--sugarsync-private-access-key',
	},
	{
		label: 'Hard Delete',
		value: 'hard_delete',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Permanently delete files if true otherwise put them in the deleted files.',
		command: '--sugarsync-hard-delete',
	},
	{
		label: 'Refresh Token',
		value: 'refresh_token',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Sugarsync refresh token. Leave blank normally, will be auto configured by rclone.',
		command: '--sugarsync-refresh-token',
	},
	{
		label: 'Authorization',
		value: 'authorization',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Sugarsync authorization. Leave blank normally, will be auto configured by rclone.',
		command: '--sugarsync-authorization',
	},
	{
		label: 'Authorization Expiry',
		value: 'authorization_expiry',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Sugarsync authorization expiry. Leave blank normally, will be auto configured by rclone.',
		command: '--sugarsync-authorization-expiry',
	},
	{
		label: 'Root ID',
		value: 'root_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Sugarsync root id. Leave blank normally, will be auto configured by rclone.',
		command: '--sugarsync-root-id',
	},
	{
		label: 'Deleted Folder ID',
		value: 'deleted_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Sugarsync deleted folder id. Leave blank normally, will be auto configured by rclone.',
		command: '--sugarsync-deleted-id',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,ctl,invalidutf8,dot',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--sugarsync-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--sugarsync-description',
	},
];

export default sugarsyncSettings;
