const swiftSettings = [
	{
		label: 'Username',
		value: 'user',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'User name to log in (OS_USERNAME).',
		command: '--swift-user',
	},
	{
		label: 'Password / API Key',
		value: 'key',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'API key or password (OS_PASSWORD).',
		command: '--swift-key',
	},
	{
		label: 'Auth URL',
		value: 'auth',
		fieldType: 'select',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'Authentication URL for server (OS_AUTH_URL).',
		options: [
			{ label: 'Rackspace US', value: 'https://auth.api.rackspacecloud.com/v1.0' },
			{ label: 'Rackspace UK', value: 'https://lon.auth.api.rackspacecloud.com/v1.0' },
			{ label: 'Rackspace V2', value: 'https://identity.api.rackspacecloud.com/v2.0' },
			{ label: 'Memset Memstore UK', value: 'https://auth.storage.memset.com/v1.0' },
			{ label: 'Memset Memstore UK v2', value: 'https://auth.storage.memset.com/v2.0' },
			{ label: 'OVH', value: 'https://auth.cloud.ovh.net/v3' },
			{ label: 'Blomp Cloud Storage', value: 'https://authenticate.ain.net' },
			{ label: 'Custom', value: 'custom' },
		],
		command: '--swift-auth',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Get swift credentials from environment variables in standard OpenStack form.',
		command: '--swift-env-auth',
	},
	{
		label: 'User ID',
		value: 'user_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'User ID to log in - optional - most swift systems use user and leave this blank (v3 auth) (OS_USER_ID).',
		command: '--swift-user-id',
	},
	{
		label: 'User Domain',
		value: 'domain',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'User domain - optional (v3 auth) (OS_USER_DOMAIN_NAME)',
		command: '--swift-domain',
	},
	{
		label: 'Tenant Name',
		value: 'tenant',
		fieldType: 'string',
		required: true,
		default: '',
		description:
			'Tenant name - optional for v1 auth, this or tenant_id required otherwise (OS_TENANT_NAME or OS_PROJECT_NAME).',
		command: '--swift-tenant',
	},
	{
		label: 'Tenant ID',
		value: 'tenant_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Tenant ID - optional for v1 auth, this or tenant required otherwise (OS_TENANT_ID).',
		command: '--swift-tenant-id',
	},
	{
		label: 'Tenant Domain',
		value: 'tenant_domain',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Tenant domain - optional (v3 auth) (OS_PROJECT_DOMAIN_NAME).',
		command: '--swift-tenant-domain',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Region name - optional (OS_REGION_NAME).',
		command: '--swift-region',
	},
	{
		label: 'Storage URL',
		value: 'storage_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Storage URL - optional (OS_STORAGE_URL).',
		command: '--swift-storage-url',
	},
	{
		label: 'Auth Token',
		value: 'auth_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth Token from alternate authentication - optional (OS_AUTH_TOKEN).',
		command: '--swift-auth-token',
	},
	{
		label: 'Application Credential ID',
		value: 'application_credential_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Application Credential ID (OS_APPLICATION_CREDENTIAL_ID).',
		command: '--swift-application-credential-id',
	},
	{
		label: 'Application Credential Name',
		value: 'application_credential_name',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Application Credential Name (OS_APPLICATION_CREDENTIAL_NAME).',
		command: '--swift-application-credential-name',
	},
	{
		label: 'Application Credential Secret',
		value: 'application_credential_secret',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Application Credential Secret (OS_APPLICATION_CREDENTIAL_SECRET).',
		command: '--swift-application-credential-secret',
	},
	{
		label: 'Auth Version',
		value: 'auth_version',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'AuthVersion - optional - set to (1,2,3) if your auth URL has no version (ST_AUTH_VERSION).',
		command: '--swift-auth-version',
	},
	{
		label: 'Endpoint Type',
		value: 'endpoint_type',
		fieldType: 'string',
		required: false,
		default: 'public',
		description: 'Endpoint type to choose from the service catalogue (OS_ENDPOINT_TYPE).',
		command: '--swift-endpoint-type',
	},
	{
		label: 'Storage Policy',
		value: 'storage_policy',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'The storage policy to use when creating a new container. This applies the specified storage policy when creating a new container. The policy cannot be changed afterwards. The allowed configuration values and their meaning depend on your Swift storage provider.',
		command: '--swift-storage-policy',
	},
	{
		label: 'Leave Parts On Error',
		value: 'leave_parts_on_error',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If true avoid calling abort upload on a failure. It should be set to true for resuming uploads across different sessions.',
		command: '--swift-leave-parts-on-error',
	},
	{
		label: 'Fetch Until Empty Page',
		value: 'fetch_until_empty_page',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'When paginating, always fetch unless we received an empty page. Consider using this option if rclone listings show fewer objects than expected, or if repeated syncs copy unchanged objects.',
		command: '--swift-fetch-until-empty-page',
	},
	{
		label: 'Partial Page Fetch Threshold',
		value: 'partial_page_fetch_threshold',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'When paginating, fetch if the current page is within this percentage of the limit. Consider using this option if rclone listings show fewer objects than expected, or if repeated syncs copy unchanged objects.',
		command: '--swift-partial-page-fetch-threshold',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '5gi',
		description:
			'Above this size files will be chunked. Above this size files will be chunked into a a _segments container or a .file-segments directory. (See the use_segments_container option for more info). Default for this is 5 GiB which is its maximum value, which means only files above this size will be chunked.',
		command: '--swift-chunk-size',
	},
	{
		label: 'No Chunk',
		value: 'no_chunk',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Don't chunk files during streaming upload. When doing streaming uploads (e.g. using rcat or mount with --vfs-cache-mode off) setting this flag will cause the swift backend to not upload chunked files.",
		command: '--swift-no-chunk',
	},
	{
		label: 'No Large Objects',
		value: 'no_large_objects',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Disable support for static and dynamic large objects Swift cannot transparently store files bigger than 5 GiB. There are two schemes for chunking large files, static large objects (SLO) or dynamic large objects (DLO), and the API does not allow rclone to determine whether a file is a static or dynamic large object without doing a HEAD on the object. Since these need to be treated differently, this means rclone has to issue HEAD requests for objects for example when reading checksums.',
		command: '--swift-no-large-objects',
	},
	{
		label: 'Use Segments Container',
		value: 'use_segments_container',
		fieldType: 'tristate',
		required: false,
		default: 'unset',
		description:
			'Choose destination for large object segments Swift cannot transparently store files bigger than 5 GiB and rclone will chunk files larger than chunk_size (default 5 GiB) in order to upload them.',
		command: '--swift-use-segments-container',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,invalidutf8',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--swift-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--swift-description',
	},
];

export default swiftSettings;
