const swiftSettings = [
	{
		label: 'Username',
		value: 'user',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'User name to log in.',
		command: '--swift-user',
	},
	{
		label: 'Password / API Key',
		value: 'key',
		fieldType: 'string',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'API key or password.',
		command: '--swift-key',
	},
	{
		label: 'Auth URL',
		value: 'auth',
		fieldType: 'select',
		authFieldType: 'password',
		required: true,
		default: '',
		description: 'Authentication URL for server.',
		options: [
			{ label: 'Rackspace US', value: 'https://auth.api.rackspacecloud.com/v1.0' },
			{ label: 'Rackspace UK', value: 'https://lon.auth.api.rackspacecloud.com/v1.0' },
			{ label: 'Rackspace V2', value: 'https://identity.api.rackspacecloud.com/v2.0' },
			{ label: 'Memset Memstore UK', value: 'https://auth.storage.memset.com/v1.0' },
			{ label: 'Memset Memstore UK v2', value: 'https://auth.storage.memset.com/v2.0' },
			{ label: 'OVH', value: 'https://auth.cloud.ovh.net/v3' },
			{ label: 'Blomp Cloud Storage', value: 'https://authenticate.ain.net' },
			{ label: 'Custom', value: 'custom' },
		],
		command: '--swift-auth',
	},
	{
		label: 'Environment Auth',
		value: 'env_auth',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Get swift credentials from environment variables in standard OpenStack form.',
		command: '--swift-env-auth',
	},
	{
		label: 'User ID',
		value: 'user_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'User ID to log in. Optional — most systems use Username instead. Only used with v3 authentication.',
		command: '--swift-user-id',
		condition: [{ auth_version: 0 }, { auth_version: 3 }],
	},
	{
		label: 'User Domain',
		value: 'domain',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'User domain. Optional, only used with v3 authentication.',
		command: '--swift-domain',
		condition: [{ auth_version: 0 }, { auth_version: 3 }],
	},
	{
		label: 'Tenant Name',
		value: 'tenant',
		fieldType: 'string',
		required: true,
		default: '',
		description:
			'Tenant name. Optional for v1 auth, otherwise this or Tenant ID is required.',
		command: '--swift-tenant',
	},
	{
		label: 'Tenant ID',
		value: 'tenant_id',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Tenant ID. Optional for v1 auth, otherwise this or Tenant Name is required.',
		command: '--swift-tenant-id',
	},
	{
		label: 'Tenant Domain',
		value: 'tenant_domain',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Tenant domain. Optional, only used with v3 authentication.',
		command: '--swift-tenant-domain',
		condition: [{ auth_version: 0 }, { auth_version: 3 }],
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Region name (optional).',
		command: '--swift-region',
	},
	{
		label: 'Storage URL',
		value: 'storage_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Storage URL (optional).',
		command: '--swift-storage-url',
	},
	{
		label: 'Auth Token',
		value: 'auth_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth token from alternate authentication (optional).',
		command: '--swift-auth-token',
	},
	{
		label: 'Application Credential ID',
		value: 'application_credential_id',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Application credential ID for authentication.',
		command: '--swift-application-credential-id',
		condition: [{ auth_version: 0 }, { auth_version: 3 }],
	},
	{
		label: 'Application Credential Name',
		value: 'application_credential_name',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Application credential name for authentication.',
		command: '--swift-application-credential-name',
		condition: [{ auth_version: 0 }, { auth_version: 3 }],
	},
	{
		label: 'Application Credential Secret',
		value: 'application_credential_secret',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Application credential secret for authentication.',
		command: '--swift-application-credential-secret',
		condition: [{ auth_version: 0 }, { auth_version: 3 }],
	},
	{
		label: 'Auth Version',
		value: 'auth_version',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'Authentication version. Set to 1, 2, or 3 if your Auth URL has no version specified.',
		command: '--swift-auth-version',
	},
	{
		label: 'Endpoint Type',
		value: 'endpoint_type',
		fieldType: 'select',
		required: false,
		default: 'public',
		description: 'Endpoint type to choose from the service catalogue.',
		command: '--swift-endpoint-type',
		options: [
			{ label: 'Public (default)', value: 'public' },
			{ label: 'Internal', value: 'internal' },
			{ label: 'Admin', value: 'admin' },
		],
	},
	{
		label: 'Storage Policy',
		value: 'storage_policy',
		fieldType: 'select',
		allowCustom: true,
		required: false,
		default: '',
		description:
			'The storage policy to use when creating a new container. This applies the specified storage policy when creating a new container. The policy cannot be changed afterwards. The allowed configuration values and their meaning depend on your Swift storage provider.',
		command: '--swift-storage-policy',
		options: [
			{ label: 'Default', value: '' },
			{ label: 'OVH Public Cloud Storage', value: 'pcs' },
			{ label: 'OVH Public Cloud Archive', value: 'pca' },
			{ label: 'Custom', value: 'custom' },
		],
	},
	{
		label: 'Leave Parts On Error',
		value: 'leave_parts_on_error',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'If true avoid calling abort upload on a failure. It should be set to true for resuming uploads across different sessions.',
		command: '--swift-leave-parts-on-error',
	},
	{
		label: 'Fetch Until Empty Page',
		value: 'fetch_until_empty_page',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'When paginating, always fetch unless an empty page is received. Enable if file listings show fewer objects than expected or repeated syncs copy unchanged objects.',
		command: '--swift-fetch-until-empty-page',
	},
	{
		label: 'Partial Page Fetch Threshold',
		value: 'partial_page_fetch_threshold',
		fieldType: 'int',
		required: false,
		default: '0',
		description:
			'When paginating, fetch if the current page is within this percentage of the limit. Enable if file listings show fewer objects than expected or repeated syncs copy unchanged objects.',
		command: '--swift-partial-page-fetch-threshold',
	},
	{
		label: 'Chunk Size',
		value: 'chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '5gi',
		description:
			'Files above this size will be chunked into segments. Default is 5 GiB, which is also the maximum value.',
		command: '--swift-chunk-size',
	},
	{
		label: 'No Chunk',
		value: 'no_chunk',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			"Don't chunk files during streaming upload.",
		command: '--swift-no-chunk',
	},
	{
		label: 'No Large Objects',
		value: 'no_large_objects',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Disable support for static and dynamic large objects. Swift cannot transparently store files bigger than 5 GiB. Enabling this may improve performance but limits large file support.',
		command: '--swift-no-large-objects',
	},
	{
		label: 'Use Segments Container',
		value: 'use_segments_container',
		fieldType: 'tristate',
		required: false,
		default: 'unset',
		description:
			'Choose destination for large object segments. Swift cannot store files bigger than 5 GiB, so files larger than the Chunk Size will be split into segments.',
		command: '--swift-use-segments-container',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'slash,invalidutf8',
		description:
			'The encoding for the backend.',
		command: '--swift-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--swift-description',
	},
];

export default swiftSettings;
