import s3Options from './_s3Options';

const wasabiSettings = [
	{
		label: 'Access Key ID',
		value: 'access_key_id',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Access Key ID.',
		command: '--s3-access-key-id',
	},
	{
		label: 'Secret Access Key',
		value: 'secret_access_key',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'Secret Access Key (password).',
		command: '--s3-secret-access-key',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'select',
		authFieldType: 'client',
		allowCustom: true,
		options: [
			{ label: 'Select Region', value: '' },
			{ label: 'US East 1 (N. Virginia)', value: 'us-east-1' },
			{ label: 'US East 2 (N. Virginia)', value: 'us-east-2' },
			{ label: 'US Central 1 (Texas)', value: 'us-central-1' },
			{ label: 'US West 1 (Oregon)', value: 'us-west-1' },
			{ label: 'CA Central 1 (Toronto)', value: 'ca-central-1' },
			{ label: 'EU Central 1 (Amsterdam)', value: 'eu-central-1' },
			{ label: 'EU Central 2 (Frankfurt)', value: 'eu-central-2' },
			{ label: 'EU West 1 (London)', value: 'eu-west-1' },
			{ label: 'EU West 2 (Paris)', value: 'eu-west-2' },
			{ label: 'EU West 3 (London)', value: 'eu-west-3' },
			{ label: 'EU South 1 (Milan)', value: 'eu-south-1' },
			{ label: 'AP Northeast 1 (Tokyo)', value: 'ap-northeast-1' },
			{ label: 'AP Northeast 2 (Osaka)', value: 'ap-northeast-2' },
			{ label: 'AP Southeast 1 (Singapore)', value: 'ap-southeast-1' },
			{ label: 'AP Southeast 2 (Sydney)', value: 'ap-southeast-2' },
			{ label: 'Insert Custon Region', value: 'custom' },
		],
		required: true,
		default: '',
		description: "Select a Region to connect to that region's API Ednpoint.",
		command: '--s3-region',
	},
	{
		label: 'ACL',
		value: 'acl',
		fieldType: 'select',
		authFieldType: 'client',
		options: [
			{ label: 'Private', value: 'private' },
			{ label: 'Public Read', value: 'public-read' },
			{ label: 'Public Read/Write', value: 'public-read-write' },
			{ label: 'Authenticated Read', value: 'authenticated-read' },
			{ label: 'Bucket Owner Read', value: 'bucket-owner-read' },
			{ label: 'Bucket Owner Full Control', value: 'bucket-owner-full-control' },
		],
		required: false,
		default: '',
		description:
			'Control lists (ACL) are subresources attached to buckets and objects. They define which Scaleway users have access to the attached object/bucket, and the type of access they have.',
		command: '--s3-acl',
	},
	...s3Options,
];

export default wasabiSettings;
