const webdavSettings = [
	{
		label: 'Server URL',
		value: 'url',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'URL of http host to connect to. E.g. https://example.com.',
		command: '--webdav-url',
	},
	{
		label: 'Vendor Name',
		value: 'vendor',
		fieldType: 'select',
		required: false,
		default: '',
		description: 'Name of the WebDAV site/service/software you are using.',
		command: '--webdav-vendor',
		options: [
			{ label: 'Fastmail Files', value: 'fastmail' },
			{ label: 'Nextcloud', value: 'nextcloud' },
			{ label: 'Owncloud', value: 'owncloud' },
			{ label: 'ownCloud Infinite Scale', value: 'infinitescale' },
			{ label: 'Sharepoint Online', value: 'sharepoint' },
			{ label: 'Sharepoint (NTLM)', value: 'sharepoint-ntlm' },
			{ label: 'rclone WebDAV', value: 'rclone' },
			{ label: 'Other', value: 'other' },
		],
	},
	{
		label: 'Username',
		value: 'user',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"User name. In case NTLM authentication is used, the username should be in the format 'Domain\\User'.",
		command: '--webdav-user',
	},
	{
		label: 'Password',
		value: 'pass',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Password.',
		command: '--webdav-pass',
	},
	{
		label: 'Bearer Token',
		value: 'bearer_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Bearer token instead of user/pass (e.g. a Macaroon).',
		command: '--webdav-bearer-token',
	},
	{
		label: 'Bearer Token Command',
		value: 'bearer_token_command',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Command to run to get a bearer token.',
		command: '--webdav-bearer-token-command',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'The encoding for the backend.',
		command: '--webdav-encoding',
	},
	{
		label: 'HTTP Headers',
		value: 'headers',
		fieldType: 'commaseplist',
		required: false,
		default: '',
		description: 'Set additional HTTP headers for all transactions.',
		command: '--webdav-headers',
	},
	{
		label: 'Pacer Min Sleep',
		value: 'pacer_min_sleep',
		fieldType: 'duration',
		required: false,
		default: '10ms',
		description: 'Minimum time to sleep between API calls.',
		command: '--webdav-pacer-min-sleep',
	},
	{
		label: 'NextCloud Chunk Size',
		value: 'nextcloud_chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description:
			'Nextcloud upload chunk size. Consider increasing the max chunk size on your Nextcloud instance for better upload performance.',
		command: '--webdav-nextcloud-chunk-size',
		condition: [{ vendor: 'nextcloud' }],
	},
	{
		label: 'Exclude OwnCloud Shares',
		value: 'owncloud_exclude_shares',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Exclude ownCloud shares',
		command: '--webdav-owncloud-exclude-shares',
		condition: [{ vendor: 'owncloud' }],
	},
	{
		label: 'Exclude OwnCloud Mounts',
		value: 'owncloud_exclude_mounts',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Exclude ownCloud mounted storages',
		command: '--webdav-owncloud-exclude-mounts',
		condition: [{ vendor: 'owncloud' }],
	},
	{
		label: 'Unix Socket Path',
		value: 'unix_socket',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to a unix domain socket to dial to, instead of opening a TCP connection directly',
		command: '--webdav-unix-socket',
	},
	{
		label: 'Auth Redirect',
		value: 'auth_redirect',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Preserve authentication on redirect. By default, authorization headers are removed when the server redirects to a different domain.',
		command: '--webdav-auth-redirect',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--webdav-description',
	},
];

export default webdavSettings;
