const webdavSettings = [
	{
		label: 'Server URL',
		value: 'url',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'URL of http host to connect to. E.g. https://example.com.',
		command: '--webdav-url',
	},
	{
		label: 'Vendor Name',
		value: 'vendor',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Name of the WebDAV site/service/software you are using.',
		command: '--webdav-vendor',
	},
	{
		label: 'Username',
		value: 'user',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			"User name. In case NTLM authentication is used, the username should be in the format 'Domain\\User'.",
		command: '--webdav-user',
	},
	{
		label: 'Password',
		value: 'pass',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Password. NB Input to this must be obscured - see rclone obscure.',
		command: '--webdav-pass',
	},
	{
		label: 'Bearer Token',
		value: 'bearer_token',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Bearer token instead of user/pass (e.g. a Macaroon).',
		command: '--webdav-bearer-token',
	},
	{
		label: 'Bearer Token Command',
		value: 'bearer_token_command',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Command to run to get a bearer token.',
		command: '--webdav-bearer-token-command',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'The encoding for the backend. See the encoding section in the overview for more info.',
		command: '--webdav-encoding',
	},
	{
		label: 'HTTP Headers',
		value: 'headers',
		fieldType: 'commaseplist',
		required: false,
		default: '',
		description:
			'Set HTTP headers for all transactions. Use this to set additional HTTP headers for all transactions',
		command: '--webdav-headers',
	},
	{
		label: 'Pacer Min Sleep',
		value: 'pacer_min_sleep',
		fieldType: 'duration',
		required: false,
		default: '10ms',
		description: 'Minimum time to sleep between API calls.',
		command: '--webdav-pacer-min-sleep',
	},
	{
		label: 'NextCloud Chunk Size',
		value: 'nextcloud_chunk_size',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description:
			'Nextcloud upload chunk size. We recommend configuring your NextCloud instance to increase the max chunk size to 1 GB for better upload performances. See https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html#adjust-chunk-size-on-nextcloud-side',
		command: '--webdav-nextcloud-chunk-size',
	},
	{
		label: 'Exclude OwnCloud Shares',
		value: 'owncloud_exclude_shares',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Exclude ownCloud shares',
		command: '--webdav-owncloud-exclude-shares',
	},
	{
		label: 'Exclude OwnCloud Mounts',
		value: 'owncloud_exclude_mounts',
		fieldType: 'bool',
		required: false,
		default: false,
		description: 'Exclude ownCloud mounted storages',
		command: '--webdav-owncloud-exclude-mounts',
	},
	{
		label: 'Unix Socket Path',
		value: 'unix_socket',
		fieldType: 'string',
		required: false,
		default: '',
		description:
			'Path to a unix domain socket to dial to, instead of opening a TCP connection directly',
		command: '--webdav-unix-socket',
	},
	{
		label: 'Auth Redirect',
		value: 'auth_redirect',
		fieldType: 'bool',
		required: false,
		default: false,
		description:
			'Preserve authentication on redirect. If the server redirects rclone to a new domain when it is trying to read a file then normally rclone will drop the Authorization: header from the request.',
		command: '--webdav-auth-redirect',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--webdav-description',
	},
];

export default webdavSettings;
