const zohoSettings = [
	{
		label: 'Client ID',
		value: 'client_id',
		authFieldType: 'client',
		fieldType: 'string',
		required: true,
		default: '',
		description: 'OAuth Client Id. Leave blank normally.',
		command: '--zoho-client-id',
	},
	{
		label: 'Client Secret',
		value: 'client_secret',
		fieldType: 'string',
		authFieldType: 'client',
		required: true,
		default: '',
		description: 'OAuth Client Secret. Leave blank normally.',
		command: '--zoho-client-secret',
	},
	{
		label: 'Region',
		value: 'region',
		fieldType: 'select',
		authFieldType: 'client',
		required: true,
		default: '',
		description:
			"Zoho region to connect to. You'll have to use the region your organization is registered in. If not sure use the same top level domain as you connect to in your browser.",
		command: '--zoho-region',
		options: [
			{ label: 'United States / Global', value: 'com' },
			{ label: 'Europe', value: 'eu' },
			{ label: 'India', value: 'in' },
			{ label: 'Japan', value: 'jp' },
			{ label: 'China', value: 'com.cn' },
			{ label: 'Australia', value: 'com.au' },
		],
	},
	{
		label: 'OAuth Access Token',
		value: 'token',
		fieldType: 'string',
		authFieldType: 'oauth',
		required: true,
		default: '',
		description: 'OAuth Access Token as a JSON blob.',
		command: '--zoho-token',
	},
	{
		label: 'Auth URL',
		value: 'auth_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Auth server URL. Leave blank to use the provider defaults.',
		command: '--zoho-auth-url',
	},
	{
		label: 'Token URL',
		value: 'token_url',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Token server url. Leave blank to use the provider defaults.',
		command: '--zoho-token-url',
	},
	{
		label: 'Client Credentials',
		value: 'client_credentials',
		fieldType: 'bool',
		authFieldType: 'client',
		required: false,
		default: false,
		description:
			'Use client credentials OAuth flow. This will use the OAUTH2 client Credentials Flow as described in RFC 6749.',
		command: '--zoho-client-credentials',
	},
	{
		label: 'Upload Cutoff',
		value: 'upload_cutoff',
		fieldType: 'sizesuffix',
		required: false,
		default: '10mi',
		description: 'Cutoff for switching to large file upload api (>= 10 MiB).',
		command: '--zoho-upload-cutoff',
	},
	{
		label: 'Encoding',
		value: 'encoding',
		fieldType: 'encoding',
		required: false,
		default: 'del,ctl,invalidutf8',
		description: 'The encoding for the backend.',
		command: '--zoho-encoding',
	},
	{
		label: 'Description',
		value: 'description',
		fieldType: 'string',
		required: false,
		default: '',
		description: 'Description of the Storage.',
		command: '--zoho-description',
	},
];

export default zohoSettings;
